/*
 * Copyright (c) 2024 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.LightHcColorTokens

/**
 * Semantic colors for the high contrast light Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsHcLight = SemanticColors(
    bgAccentHovered = LightHcColorTokens.Color(0xff004d36),
    bgAccentPressed = LightHcColorTokens.Color(0xff00402b),
    bgAccentRest = LightHcColorTokens.Color(0xff00553d),
    bgActionPrimaryDisabled = LightHcColorTokens.Color(0xff878f9b),
    bgActionPrimaryHovered = LightHcColorTokens.Color(0xff2d3034),
    bgActionPrimaryPressed = LightHcColorTokens.Color(0xff35383d),
    bgActionPrimaryRest = LightHcColorTokens.Color(0xff1a1c21),
    bgActionSecondaryHovered = LightHcColorTokens.Color(0x0f052657),
    bgActionSecondaryPressed = LightHcColorTokens.Color(0x1f052e61),
    bgActionSecondaryRest = LightHcColorTokens.Color(0xffffffff),
    bgCanvasDefault = LightHcColorTokens.Color(0xffffffff),
    bgCanvasDisabled = LightHcColorTokens.Color(0xfff0f2f5),
    bgCriticalHovered = LightHcColorTokens.Color(0xff8b000c),
    bgCriticalPrimary = LightHcColorTokens.Color(0xff99001a),
    bgCriticalSubtle = LightHcColorTokens.Color(0xffffefec),
    bgCriticalSubtleHovered = LightHcColorTokens.Color(0xffffdfda),
    bgDecorative1 = LightHcColorTokens.Color(0xffc8f1ba),
    bgDecorative2 = LightHcColorTokens.Color(0xffc7ecf0),
    bgDecorative3 = LightHcColorTokens.Color(0xfff6dff7),
    bgDecorative4 = LightHcColorTokens.Color(0xffe6e2ff),
    bgDecorative5 = LightHcColorTokens.Color(0xffffdee5),
    bgDecorative6 = LightHcColorTokens.Color(0xffffdfc8),
    bgInfoSubtle = LightHcColorTokens.Color(0xffe9f2ff),
    bgSubtlePrimary = LightHcColorTokens.Color(0xffd7dce3),
    bgSubtleSecondary = LightHcColorTokens.Color(0xffe1e6ec),
    bgSuccessSubtle = LightHcColorTokens.Color(0xffe3f7ed),
    borderCriticalHovered = LightHcColorTokens.Color(0xff8b000c),
    borderCriticalPrimary = LightHcColorTokens.Color(0xff99001a),
    borderCriticalSubtle = LightHcColorTokens.Color(0xffffafa5),
    borderDisabled = LightHcColorTokens.Color(0xffbdc4cc),
    borderFocused = LightHcColorTokens.Color(0xff0543a7),
    borderInfoSubtle = LightHcColorTokens.Color(0xffa3c6fa),
    borderInteractiveHovered = LightHcColorTokens.Color(0xff35383d),
    borderInteractivePrimary = LightHcColorTokens.Color(0xff6c737e),
    borderInteractiveSecondary = LightHcColorTokens.Color(0xffa6adb7),
    borderSuccessSubtle = LightHcColorTokens.Color(0xff71d7ae),
    iconAccentPrimary = LightHcColorTokens.Color(0xff00553d),
    iconAccentTertiary = LightHcColorTokens.Color(0xff008268),
    iconCriticalPrimary = LightHcColorTokens.Color(0xff99001a),
    iconDisabled = LightHcColorTokens.Color(0xff878f9b),
    iconInfoPrimary = LightHcColorTokens.Color(0xff0543a7),
    iconOnSolidPrimary = LightHcColorTokens.Color(0xffffffff),
    iconPrimary = LightHcColorTokens.Color(0xff1a1c21),
    iconPrimaryAlpha = LightHcColorTokens.Color(0xe6010309),
    iconQuaternary = LightHcColorTokens.Color(0xff878f9b),
    iconQuaternaryAlpha = LightHcColorTokens.Color(0x7a05152e),
    iconSecondary = LightHcColorTokens.Color(0xff474a51),
    iconSecondaryAlpha = LightHcColorTokens.Color(0xba030711),
    iconSuccessPrimary = LightHcColorTokens.Color(0xff00553d),
    iconTertiary = LightHcColorTokens.Color(0xff6c737e),
    iconTertiaryAlpha = LightHcColorTokens.Color(0x94020e22),
    textActionAccent = LightHcColorTokens.Color(0xff00553d),
    textActionPrimary = LightHcColorTokens.Color(0xff1a1c21),
    textCriticalPrimary = LightHcColorTokens.Color(0xff99001a),
    textDecorative1 = LightHcColorTokens.Color(0xff004200),
    textDecorative2 = LightHcColorTokens.Color(0xff00376e),
    textDecorative3 = LightHcColorTokens.Color(0xff5c0f76),
    textDecorative4 = LightHcColorTokens.Color(0xff4200a6),
    textDecorative5 = LightHcColorTokens.Color(0xff72003a),
    textDecorative6 = LightHcColorTokens.Color(0xff770000),
    textDisabled = LightHcColorTokens.Color(0xff6c737e),
    textInfoPrimary = LightHcColorTokens.Color(0xff0543a7),
    textLinkExternal = LightHcColorTokens.Color(0xff0543a7),
    textOnSolidPrimary = LightHcColorTokens.Color(0xffffffff),
    textPrimary = LightHcColorTokens.Color(0xff1a1c21),
    textSecondary = LightHcColorTokens.Color(0xff474a51),
    textSuccessPrimary = LightHcColorTokens.Color(0xff00553d),
    isLight = true,
)
