/*
 * Copyright (c) 2024 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.DarkHcColorTokens

/**
 * Semantic colors for the high contrast dark Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsHcDark = SemanticColors(
    bgAccentHovered = DarkHcColorTokens.colorGreen1000,
    bgAccentPressed = DarkHcColorTokens.colorGreen1100,
    bgAccentRest = DarkHcColorTokens.colorGreen900,
    bgActionPrimaryDisabled = DarkHcColorTokens.colorGray700,
    bgActionPrimaryHovered = DarkHcColorTokens.colorGray1200,
    bgActionPrimaryPressed = DarkHcColorTokens.colorGray1100,
    bgActionPrimaryRest = DarkHcColorTokens.colorGray1400,
    bgActionSecondaryHovered = DarkHcColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = DarkHcColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = DarkHcColorTokens.colorThemeBg,
    bgCanvasDefault = DarkHcColorTokens.colorThemeBg,
    bgCanvasDisabled = DarkHcColorTokens.colorGray200,
    bgCriticalHovered = DarkHcColorTokens.colorRed1000,
    bgCriticalPrimary = DarkHcColorTokens.colorRed900,
    bgCriticalSubtle = DarkHcColorTokens.colorRed200,
    bgCriticalSubtleHovered = DarkHcColorTokens.colorRed300,
    bgDecorative1 = DarkHcColorTokens.colorLime300,
    bgDecorative2 = DarkHcColorTokens.colorCyan300,
    bgDecorative3 = DarkHcColorTokens.colorFuchsia300,
    bgDecorative4 = DarkHcColorTokens.colorPurple300,
    bgDecorative5 = DarkHcColorTokens.colorPink300,
    bgDecorative6 = DarkHcColorTokens.colorOrange300,
    bgInfoSubtle = DarkHcColorTokens.colorBlue200,
    bgSubtlePrimary = DarkHcColorTokens.colorGray400,
    bgSubtleSecondary = DarkHcColorTokens.colorGray300,
    bgSuccessSubtle = DarkHcColorTokens.colorGreen200,
    borderCriticalHovered = DarkHcColorTokens.colorRed1000,
    borderCriticalPrimary = DarkHcColorTokens.colorRed900,
    borderCriticalSubtle = DarkHcColorTokens.colorRed500,
    borderDisabled = DarkHcColorTokens.colorGray500,
    borderFocused = DarkHcColorTokens.colorBlue900,
    borderInfoSubtle = DarkHcColorTokens.colorBlue500,
    borderInteractiveHovered = DarkHcColorTokens.colorGray1100,
    borderInteractivePrimary = DarkHcColorTokens.colorGray800,
    borderInteractiveSecondary = DarkHcColorTokens.colorGray600,
    borderSuccessSubtle = DarkHcColorTokens.colorGreen500,
    iconAccentPrimary = DarkHcColorTokens.colorGreen900,
    iconAccentTertiary = DarkHcColorTokens.colorGreen800,
    iconCriticalPrimary = DarkHcColorTokens.colorRed900,
    iconDisabled = DarkHcColorTokens.colorGray700,
    iconInfoPrimary = DarkHcColorTokens.colorBlue900,
    iconOnSolidPrimary = DarkHcColorTokens.colorThemeBg,
    iconPrimary = DarkHcColorTokens.colorGray1400,
    iconPrimaryAlpha = DarkHcColorTokens.colorAlphaGray1400,
    iconQuaternary = DarkHcColorTokens.colorGray700,
    iconQuaternaryAlpha = DarkHcColorTokens.colorAlphaGray700,
    iconSecondary = DarkHcColorTokens.colorGray900,
    iconSecondaryAlpha = DarkHcColorTokens.colorAlphaGray900,
    iconSuccessPrimary = DarkHcColorTokens.colorGreen900,
    iconTertiary = DarkHcColorTokens.colorGray800,
    iconTertiaryAlpha = DarkHcColorTokens.colorAlphaGray800,
    textActionAccent = DarkHcColorTokens.colorGreen900,
    textActionPrimary = DarkHcColorTokens.colorGray1400,
    textCriticalPrimary = DarkHcColorTokens.colorRed900,
    textDecorative1 = DarkHcColorTokens.colorLime1100,
    textDecorative2 = DarkHcColorTokens.colorCyan1100,
    textDecorative3 = DarkHcColorTokens.colorFuchsia1100,
    textDecorative4 = DarkHcColorTokens.colorPurple1100,
    textDecorative5 = DarkHcColorTokens.colorPink1100,
    textDecorative6 = DarkHcColorTokens.colorOrange1100,
    textDisabled = DarkHcColorTokens.colorGray800,
    textInfoPrimary = DarkHcColorTokens.colorBlue900,
    textLinkExternal = DarkHcColorTokens.colorBlue900,
    textOnSolidPrimary = DarkHcColorTokens.colorThemeBg,
    textPlaceholder = DarkHcColorTokens.colorGray800,
    textPrimary = DarkHcColorTokens.colorGray1400,
    textSecondary = DarkHcColorTokens.colorGray900,
    textSuccessPrimary = DarkHcColorTokens.colorGreen900,
    isLight = false,
)
