/*
 * Copyright 2025 New Vector Ltd.
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial
 * Please see LICENSE files in the repository root for full details.
 */

/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.DarkHcColorTokens

/**
 * Semantic colors for the high contrast dark Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsHcDark = SemanticColors(
    bgAccentHovered = DarkHcColorTokens.colorBlue1000,
    bgAccentPressed = DarkHcColorTokens.colorBlue1100,
    bgAccentRest = DarkHcColorTokens.colorBlue900,
    bgActionPrimaryDisabled = DarkHcColorTokens.colorBlue800,
    bgActionPrimaryHovered = DarkHcColorTokens.colorBlue1100,
    bgActionPrimaryPressed = DarkHcColorTokens.colorBlue1000,
    bgActionPrimaryRest = DarkHcColorTokens.colorBlue1200,
    bgActionSecondaryHovered = DarkHcColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = DarkHcColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = DarkHcColorTokens.colorThemeBg,
    bgCanvasDefault = DarkHcColorTokens.colorThemeBg,
    bgCanvasDefaultLevel1 = DarkHcColorTokens.colorGray300,
    bgCanvasDisabled = DarkHcColorTokens.colorGray200,
    bgCriticalHovered = DarkHcColorTokens.colorRed1000,
    bgCriticalPrimary = DarkHcColorTokens.colorRed900,
    bgCriticalSubtle = DarkHcColorTokens.colorRed200,
    bgCriticalSubtleHovered = DarkHcColorTokens.colorRed300,
    bgDecorative1 = DarkHcColorTokens.colorLime300,
    bgDecorative2 = DarkHcColorTokens.colorCyan300,
    bgDecorative3 = DarkHcColorTokens.colorFuchsia300,
    bgDecorative4 = DarkHcColorTokens.colorPurple300,
    bgDecorative5 = DarkHcColorTokens.colorPink300,
    bgDecorative6 = DarkHcColorTokens.colorOrange300,
    bgInfoSubtle = DarkHcColorTokens.colorBlue200,
    bgSubtlePrimary = DarkHcColorTokens.colorGray400,
    bgSubtleSecondary = DarkHcColorTokens.colorGray300,
    bgSubtleSecondaryLevel0 = DarkHcColorTokens.colorThemeBg,
    bgSuccessSubtle = DarkHcColorTokens.colorGreen200,
    borderCriticalHovered = DarkHcColorTokens.colorRed1000,
    borderCriticalPrimary = DarkHcColorTokens.colorRed900,
    borderCriticalSubtle = DarkHcColorTokens.colorRed500,
    borderDisabled = DarkHcColorTokens.colorGray500,
    borderFocused = DarkHcColorTokens.colorBlue900,
    borderInfoSubtle = DarkHcColorTokens.colorBlue500,
    borderInteractiveHovered = DarkHcColorTokens.colorGray1100,
    borderInteractivePrimary = DarkHcColorTokens.colorGray800,
    borderInteractiveSecondary = DarkHcColorTokens.colorGray600,
    borderSuccessSubtle = DarkHcColorTokens.colorGreen500,
    iconAccentPrimary = DarkHcColorTokens.colorBlue1400,
    iconAccentTertiary = DarkHcColorTokens.colorBlue1200,
    iconCriticalPrimary = DarkHcColorTokens.colorRed900,
    iconDisabled = DarkHcColorTokens.colorGray700,
    iconInfoPrimary = DarkHcColorTokens.colorBlue900,
    iconOnSolidPrimary = DarkHcColorTokens.colorThemeBg,
    iconPrimary = DarkHcColorTokens.colorBlue1200,
    iconPrimaryAlpha = DarkHcColorTokens.colorAlphaGray1400,
    iconQuaternary = DarkHcColorTokens.colorGray700,
    iconQuaternaryAlpha = DarkHcColorTokens.colorAlphaGray700,
    iconSecondary = DarkHcColorTokens.colorGray900,
    iconSecondaryAlpha = DarkHcColorTokens.colorAlphaGray900,
    iconSuccessPrimary = DarkHcColorTokens.colorGreen900,
    iconTertiary = DarkHcColorTokens.colorGray800,
    iconTertiaryAlpha = DarkHcColorTokens.colorAlphaGray800,
    textActionAccent = DarkHcColorTokens.colorBlue1200,
    textActionPrimary = DarkHcColorTokens.colorGray1400,
    textCriticalPrimary = DarkHcColorTokens.colorRed900,
    textDecorative1 = DarkHcColorTokens.colorLime1100,
    textDecorative2 = DarkHcColorTokens.colorCyan1100,
    textDecorative3 = DarkHcColorTokens.colorFuchsia1100,
    textDecorative4 = DarkHcColorTokens.colorPurple1100,
    textDecorative5 = DarkHcColorTokens.colorPink1100,
    textDecorative6 = DarkHcColorTokens.colorOrange1100,
    textDisabled = DarkHcColorTokens.colorGray800,
    textInfoPrimary = DarkHcColorTokens.colorBlue900,
    textLinkExternal = DarkHcColorTokens.colorBlue900,
    textOnSolidPrimary = DarkHcColorTokens.colorThemeBg,
    textPrimary = DarkHcColorTokens.colorGray1400,
    textSecondary = DarkHcColorTokens.colorGray900,
    textSuccessPrimary = DarkHcColorTokens.colorGreen900,
    isLight = false,
)
