/*
 * Copyright (c) 2024 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.LightColorTokens

/**
 * Semantic colors for the light Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsLight = SemanticColors(
    bgAccentHovered = LightColorTokens.colorGreen1000,
    bgAccentPressed = LightColorTokens.colorGreen1100,
    bgAccentRest = LightColorTokens.colorGreen900,
    bgActionPrimaryDisabled = LightColorTokens.colorGray700,
    bgActionPrimaryHovered = LightColorTokens.colorGray1200,
    bgActionPrimaryPressed = LightColorTokens.colorGray1100,
    bgActionPrimaryRest = LightColorTokens.colorGray1400,
    bgActionSecondaryHovered = LightColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = LightColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = LightColorTokens.colorThemeBg,
    bgCanvasDefault = LightColorTokens.colorThemeBg,
    bgCanvasDefaultLevel1 = LightColorTokens.colorThemeBg,
    bgCanvasDisabled = LightColorTokens.colorGray200,
    bgCriticalHovered = LightColorTokens.colorRed1000,
    bgCriticalPrimary = LightColorTokens.colorRed900,
    bgCriticalSubtle = LightColorTokens.colorRed200,
    bgCriticalSubtleHovered = LightColorTokens.colorRed300,
    bgDecorative1 = LightColorTokens.colorLime300,
    bgDecorative2 = LightColorTokens.colorCyan300,
    bgDecorative3 = LightColorTokens.colorFuchsia300,
    bgDecorative4 = LightColorTokens.colorPurple300,
    bgDecorative5 = LightColorTokens.colorPink300,
    bgDecorative6 = LightColorTokens.colorOrange300,
    bgInfoSubtle = LightColorTokens.colorBlue200,
    bgSubtlePrimary = LightColorTokens.colorGray400,
    bgSubtleSecondary = LightColorTokens.colorGray300,
    bgSubtleSecondaryLevel0 = LightColorTokens.colorGray300,
    bgSuccessSubtle = LightColorTokens.colorGreen200,
    borderCriticalHovered = LightColorTokens.colorRed1000,
    borderCriticalPrimary = LightColorTokens.colorRed900,
    borderCriticalSubtle = LightColorTokens.colorRed500,
    borderDisabled = LightColorTokens.colorGray500,
    borderFocused = LightColorTokens.colorBlue900,
    borderInfoSubtle = LightColorTokens.colorBlue500,
    borderInteractiveHovered = LightColorTokens.colorGray1100,
    borderInteractivePrimary = LightColorTokens.colorGray800,
    borderInteractiveSecondary = LightColorTokens.colorGray600,
    borderSuccessSubtle = LightColorTokens.colorGreen500,
    iconAccentPrimary = LightColorTokens.colorGreen900,
    iconAccentTertiary = LightColorTokens.colorGreen800,
    iconCriticalPrimary = LightColorTokens.colorRed900,
    iconDisabled = LightColorTokens.colorGray700,
    iconInfoPrimary = LightColorTokens.colorBlue900,
    iconOnSolidPrimary = LightColorTokens.colorThemeBg,
    iconPrimary = LightColorTokens.colorGray1400,
    iconPrimaryAlpha = LightColorTokens.colorAlphaGray1400,
    iconQuaternary = LightColorTokens.colorGray700,
    iconQuaternaryAlpha = LightColorTokens.colorAlphaGray700,
    iconSecondary = LightColorTokens.colorGray900,
    iconSecondaryAlpha = LightColorTokens.colorAlphaGray900,
    iconSuccessPrimary = LightColorTokens.colorGreen900,
    iconTertiary = LightColorTokens.colorGray800,
    iconTertiaryAlpha = LightColorTokens.colorAlphaGray800,
    textActionAccent = LightColorTokens.colorGreen900,
    textActionPrimary = LightColorTokens.colorGray1400,
    textCriticalPrimary = LightColorTokens.colorRed900,
    textDecorative1 = LightColorTokens.colorLime1100,
    textDecorative2 = LightColorTokens.colorCyan1100,
    textDecorative3 = LightColorTokens.colorFuchsia1100,
    textDecorative4 = LightColorTokens.colorPurple1100,
    textDecorative5 = LightColorTokens.colorPink1100,
    textDecorative6 = LightColorTokens.colorOrange1100,
    textDisabled = LightColorTokens.colorGray800,
    textInfoPrimary = LightColorTokens.colorBlue900,
    textLinkExternal = LightColorTokens.colorBlue900,
    textOnSolidPrimary = LightColorTokens.colorThemeBg,
    textPrimary = LightColorTokens.colorGray1400,
    textSecondary = LightColorTokens.colorGray900,
    textSuccessPrimary = LightColorTokens.colorGreen900,
    isLight = true,
)
