/*
 * Copyright (c) 2024 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.LightColorTokens

/**
 * Semantic colors for the light Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsLight = SemanticColors(
    bgAccentHovered = LightColorTokens.Color(0xff006b52),
    bgAccentPressed = LightColorTokens.Color(0xff005c45),
    bgAccentRest = LightColorTokens.Color(0xff007a61),
    bgActionPrimaryDisabled = LightColorTokens.Color(0xffa6adb7),
    bgActionPrimaryHovered = LightColorTokens.Color(0xff3c4045),
    bgActionPrimaryPressed = LightColorTokens.Color(0xff4c5158),
    bgActionPrimaryRest = LightColorTokens.Color(0xff1b1d22),
    bgActionSecondaryHovered = LightColorTokens.Color(0x0a366881),
    bgActionSecondaryPressed = LightColorTokens.Color(0x0f052657),
    bgActionSecondaryRest = LightColorTokens.Color(0xffffffff),
    bgCanvasDefault = LightColorTokens.Color(0xffffffff),
    bgCanvasDisabled = LightColorTokens.Color(0xfff7f9fa),
    bgCriticalHovered = LightColorTokens.Color(0xffbc0f22),
    bgCriticalPrimary = LightColorTokens.Color(0xffd51928),
    bgCriticalSubtle = LightColorTokens.Color(0xfffff7f6),
    bgCriticalSubtleHovered = LightColorTokens.Color(0xffffefec),
    bgDecorative1 = LightColorTokens.Color(0xffe0f8d9),
    bgDecorative2 = LightColorTokens.Color(0xffe3f5f8),
    bgDecorative3 = LightColorTokens.Color(0xfffaeefb),
    bgDecorative4 = LightColorTokens.Color(0xfff1efff),
    bgDecorative5 = LightColorTokens.Color(0xffffecf0),
    bgDecorative6 = LightColorTokens.Color(0xffffefe4),
    bgInfoSubtle = LightColorTokens.Color(0xfff4f8ff),
    bgSubtlePrimary = LightColorTokens.Color(0xffe1e6ec),
    bgSubtleSecondary = LightColorTokens.Color(0xfff0f2f5),
    bgSuccessSubtle = LightColorTokens.Color(0xfff1fbf6),
    borderCriticalHovered = LightColorTokens.Color(0xffbc0f22),
    borderCriticalPrimary = LightColorTokens.Color(0xffd51928),
    borderCriticalSubtle = LightColorTokens.Color(0xffffc5bc),
    borderDisabled = LightColorTokens.Color(0xffcdd3da),
    borderFocused = LightColorTokens.Color(0xff0467dd),
    borderInfoSubtle = LightColorTokens.Color(0xffbad5fc),
    borderInteractiveHovered = LightColorTokens.Color(0xff4c5158),
    borderInteractivePrimary = LightColorTokens.Color(0xff818a95),
    borderInteractiveSecondary = LightColorTokens.Color(0xffbdc4cc),
    borderSuccessSubtle = LightColorTokens.Color(0xff98e1c1),
    iconAccentPrimary = LightColorTokens.Color(0xff007a61),
    iconAccentTertiary = LightColorTokens.Color(0xff009b78),
    iconCriticalPrimary = LightColorTokens.Color(0xffd51928),
    iconDisabled = LightColorTokens.Color(0xffa6adb7),
    iconInfoPrimary = LightColorTokens.Color(0xff0467dd),
    iconOnSolidPrimary = LightColorTokens.Color(0xffffffff),
    iconPrimary = LightColorTokens.Color(0xff1b1d22),
    iconPrimaryAlpha = LightColorTokens.Color(0xe6020408),
    iconQuaternary = LightColorTokens.Color(0xffa6adb7),
    iconQuaternaryAlpha = LightColorTokens.Color(0x59011532),
    iconSecondary = LightColorTokens.Color(0xff656d77),
    iconSecondaryAlpha = LightColorTokens.Color(0x9c031021),
    iconSuccessPrimary = LightColorTokens.Color(0xff007a61),
    iconTertiary = LightColorTokens.Color(0xff818a95),
    iconTertiaryAlpha = LightColorTokens.Color(0x8003152b),
    textActionAccent = LightColorTokens.Color(0xff007a61),
    textActionPrimary = LightColorTokens.Color(0xff1b1d22),
    textCriticalPrimary = LightColorTokens.Color(0xffd51928),
    textDecorative1 = LightColorTokens.Color(0xff005f00),
    textDecorative2 = LightColorTokens.Color(0xff00548c),
    textDecorative3 = LightColorTokens.Color(0xff822198),
    textDecorative4 = LightColorTokens.Color(0xff5d26cd),
    textDecorative5 = LightColorTokens.Color(0xff9f0850),
    textDecorative6 = LightColorTokens.Color(0xff9b2200),
    textDisabled = LightColorTokens.Color(0xff818a95),
    textInfoPrimary = LightColorTokens.Color(0xff0467dd),
    textLinkExternal = LightColorTokens.Color(0xff0467dd),
    textOnSolidPrimary = LightColorTokens.Color(0xffffffff),
    textPrimary = LightColorTokens.Color(0xff1b1d22),
    textSecondary = LightColorTokens.Color(0xff656d77),
    textSuccessPrimary = LightColorTokens.Color(0xff007a61),
    isLight = true,
)
