/*
 * Copyright (c) 2024 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.DarkHcColorTokens

/**
 * Semantic colors for the high contrast dark Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsHcDark = SemanticColors(
    bgAccentHovered = DarkHcColorTokens.Color(0xff61d2a6),
    bgAccentPressed = DarkHcColorTokens.Color(0xff8fddbc),
    bgAccentRest = DarkHcColorTokens.Color(0xff37c998),
    bgActionPrimaryDisabled = DarkHcColorTokens.Color(0xff606770),
    bgActionPrimaryHovered = DarkHcColorTokens.Color(0xffd5dae1),
    bgActionPrimaryPressed = DarkHcColorTokens.Color(0xffc8ced5),
    bgActionPrimaryRest = DarkHcColorTokens.Color(0xfff2f5f7),
    bgActionSecondaryHovered = DarkHcColorTokens.Color(0x0fe9dbf0),
    bgActionSecondaryPressed = DarkHcColorTokens.Color(0x1aede7f4),
    bgActionSecondaryRest = DarkHcColorTokens.Color(0xff101317),
    bgCanvasDefault = DarkHcColorTokens.Color(0xff101317),
    bgCanvasDisabled = DarkHcColorTokens.Color(0xff1d1f24),
    bgCriticalHovered = DarkHcColorTokens.Color(0xffffa79d),
    bgCriticalPrimary = DarkHcColorTokens.Color(0xffff968c),
    bgCriticalSubtle = DarkHcColorTokens.Color(0xff470000),
    bgCriticalSubtleHovered = DarkHcColorTokens.Color(0xff590000),
    bgDecorative1 = DarkHcColorTokens.Color(0xff003000),
    bgDecorative2 = DarkHcColorTokens.Color(0xff002559),
    bgDecorative3 = DarkHcColorTokens.Color(0xff46005e),
    bgDecorative4 = DarkHcColorTokens.Color(0xff2c0080),
    bgDecorative5 = DarkHcColorTokens.Color(0xff550024),
    bgDecorative6 = DarkHcColorTokens.Color(0xff580000),
    bgInfoSubtle = DarkHcColorTokens.Color(0xff001264),
    bgSubtlePrimary = DarkHcColorTokens.Color(0xff2b2e33),
    bgSubtleSecondary = DarkHcColorTokens.Color(0xff26282d),
    bgSuccessSubtle = DarkHcColorTokens.Color(0xff002513),
    borderCriticalHovered = DarkHcColorTokens.Color(0xffffa79d),
    borderCriticalPrimary = DarkHcColorTokens.Color(0xffff968c),
    borderCriticalSubtle = DarkHcColorTokens.Color(0xff830009),
    borderDisabled = DarkHcColorTokens.Color(0xff3c3f44),
    borderFocused = DarkHcColorTokens.Color(0xff89b5f6),
    borderInfoSubtle = DarkHcColorTokens.Color(0xff083891),
    borderInteractiveHovered = DarkHcColorTokens.Color(0xffc8ced5),
    borderInteractivePrimary = DarkHcColorTokens.Color(0xff79818d),
    borderInteractiveSecondary = DarkHcColorTokens.Color(0xff4a4f55),
    borderSuccessSubtle = DarkHcColorTokens.Color(0xff004832),
    iconAccentPrimary = DarkHcColorTokens.Color(0xff37c998),
    iconAccentTertiary = DarkHcColorTokens.Color(0xff109173),
    iconCriticalPrimary = DarkHcColorTokens.Color(0xffff968c),
    iconDisabled = DarkHcColorTokens.Color(0xff606770),
    iconInfoPrimary = DarkHcColorTokens.Color(0xff89b5f6),
    iconOnSolidPrimary = DarkHcColorTokens.Color(0xff101317),
    iconPrimary = DarkHcColorTokens.Color(0xfff2f5f7),
    iconPrimaryAlpha = DarkHcColorTokens.Color(0xf7fbfdfe),
    iconQuaternary = DarkHcColorTokens.Color(0xff606770),
    iconQuaternaryAlpha = DarkHcColorTokens.Color(0x63dfebfb),
    iconSecondary = DarkHcColorTokens.Color(0xffacb4bd),
    iconSecondaryAlpha = DarkHcColorTokens.Color(0xb8ecf4fe),
    iconSuccessPrimary = DarkHcColorTokens.Color(0xff37c998),
    iconTertiary = DarkHcColorTokens.Color(0xff79818d),
    iconTertiaryAlpha = DarkHcColorTokens.Color(0x82dceafe),
    textActionAccent = DarkHcColorTokens.Color(0xff37c998),
    textActionPrimary = DarkHcColorTokens.Color(0xfff2f5f7),
    textCriticalPrimary = DarkHcColorTokens.Color(0xffff968c),
    textDecorative1 = DarkHcColorTokens.Color(0xff92e175),
    textDecorative2 = DarkHcColorTokens.Color(0xff93d9e2),
    textDecorative3 = DarkHcColorTokens.Color(0xffeac0ed),
    textDecorative4 = DarkHcColorTokens.Color(0xffcec7ff),
    textDecorative5 = DarkHcColorTokens.Color(0xffffbbca),
    textDecorative6 = DarkHcColorTokens.Color(0xfffdc197),
    textDisabled = DarkHcColorTokens.Color(0xff79818d),
    textInfoPrimary = DarkHcColorTokens.Color(0xff89b5f6),
    textLinkExternal = DarkHcColorTokens.Color(0xff89b5f6),
    textOnSolidPrimary = DarkHcColorTokens.Color(0xff101317),
    textPrimary = DarkHcColorTokens.Color(0xfff2f5f7),
    textSecondary = DarkHcColorTokens.Color(0xffacb4bd),
    textSuccessPrimary = DarkHcColorTokens.Color(0xff37c998),
    isLight = false,
)
