/*
 * Copyright (c) 2024 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.LightHcColorTokens

/**
 * Semantic colors for the high contrast light Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsHcLight = SemanticColors(
    bgAccentHovered = LightHcColorTokens.colorGreen1000,
    bgAccentPressed = LightHcColorTokens.colorGreen1100,
    bgAccentRest = LightHcColorTokens.colorGreen900,
    bgActionPrimaryDisabled = LightHcColorTokens.colorGray700,
    bgActionPrimaryHovered = LightHcColorTokens.colorGray1200,
    bgActionPrimaryPressed = LightHcColorTokens.colorGray1100,
    bgActionPrimaryRest = LightHcColorTokens.colorGray1400,
    bgActionSecondaryHovered = LightHcColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = LightHcColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = LightHcColorTokens.colorThemeBg,
    bgCanvasDefault = LightHcColorTokens.colorThemeBg,
    bgCanvasDefaultLevel1 = LightHcColorTokens.colorThemeBg,
    bgCanvasDisabled = LightHcColorTokens.colorGray200,
    bgCriticalHovered = LightHcColorTokens.colorRed1000,
    bgCriticalPrimary = LightHcColorTokens.colorRed900,
    bgCriticalSubtle = LightHcColorTokens.colorRed200,
    bgCriticalSubtleHovered = LightHcColorTokens.colorRed300,
    bgDecorative1 = LightHcColorTokens.colorLime300,
    bgDecorative2 = LightHcColorTokens.colorCyan300,
    bgDecorative3 = LightHcColorTokens.colorFuchsia300,
    bgDecorative4 = LightHcColorTokens.colorPurple300,
    bgDecorative5 = LightHcColorTokens.colorPink300,
    bgDecorative6 = LightHcColorTokens.colorOrange300,
    bgInfoSubtle = LightHcColorTokens.colorBlue200,
    bgSubtlePrimary = LightHcColorTokens.colorGray400,
    bgSubtleSecondary = LightHcColorTokens.colorGray300,
    bgSubtleSecondaryLevel0 = LightHcColorTokens.colorGray300,
    bgSuccessSubtle = LightHcColorTokens.colorGreen200,
    borderCriticalHovered = LightHcColorTokens.colorRed1000,
    borderCriticalPrimary = LightHcColorTokens.colorRed900,
    borderCriticalSubtle = LightHcColorTokens.colorRed500,
    borderDisabled = LightHcColorTokens.colorGray500,
    borderFocused = LightHcColorTokens.colorBlue900,
    borderInfoSubtle = LightHcColorTokens.colorBlue500,
    borderInteractiveHovered = LightHcColorTokens.colorGray1100,
    borderInteractivePrimary = LightHcColorTokens.colorGray800,
    borderInteractiveSecondary = LightHcColorTokens.colorGray600,
    borderSuccessSubtle = LightHcColorTokens.colorGreen500,
    iconAccentPrimary = LightHcColorTokens.colorGreen900,
    iconAccentTertiary = LightHcColorTokens.colorGreen800,
    iconCriticalPrimary = LightHcColorTokens.colorRed900,
    iconDisabled = LightHcColorTokens.colorGray700,
    iconInfoPrimary = LightHcColorTokens.colorBlue900,
    iconOnSolidPrimary = LightHcColorTokens.colorThemeBg,
    iconPrimary = LightHcColorTokens.colorGray1400,
    iconPrimaryAlpha = LightHcColorTokens.colorAlphaGray1400,
    iconQuaternary = LightHcColorTokens.colorGray700,
    iconQuaternaryAlpha = LightHcColorTokens.colorAlphaGray700,
    iconSecondary = LightHcColorTokens.colorGray900,
    iconSecondaryAlpha = LightHcColorTokens.colorAlphaGray900,
    iconSuccessPrimary = LightHcColorTokens.colorGreen900,
    iconTertiary = LightHcColorTokens.colorGray800,
    iconTertiaryAlpha = LightHcColorTokens.colorAlphaGray800,
    textActionAccent = LightHcColorTokens.colorGreen900,
    textActionPrimary = LightHcColorTokens.colorGray1400,
    textCriticalPrimary = LightHcColorTokens.colorRed900,
    textDecorative1 = LightHcColorTokens.colorLime1100,
    textDecorative2 = LightHcColorTokens.colorCyan1100,
    textDecorative3 = LightHcColorTokens.colorFuchsia1100,
    textDecorative4 = LightHcColorTokens.colorPurple1100,
    textDecorative5 = LightHcColorTokens.colorPink1100,
    textDecorative6 = LightHcColorTokens.colorOrange1100,
    textDisabled = LightHcColorTokens.colorGray800,
    textInfoPrimary = LightHcColorTokens.colorBlue900,
    textLinkExternal = LightHcColorTokens.colorBlue900,
    textOnSolidPrimary = LightHcColorTokens.colorThemeBg,
    textPrimary = LightHcColorTokens.colorGray1400,
    textSecondary = LightHcColorTokens.colorGray900,
    textSuccessPrimary = LightHcColorTokens.colorGreen900,
    isLight = true,
)
