/*
 * Copyright (c) 2024 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */



@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.DarkColorTokens

/**
 * Semantic colors for the dark Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsDark = SemanticColors(
    bgAccentHovered = DarkColorTokens.Color(0xff17ac84),
    bgAccentPressed = DarkColorTokens.Color(0xff1fc090),
    bgAccentRest = DarkColorTokens.Color(0xff129a78),
    bgActionPrimaryDisabled = DarkColorTokens.Color(0xff4a4f55),
    bgActionPrimaryHovered = DarkColorTokens.Color(0xffbdc3cc),
    bgActionPrimaryPressed = DarkColorTokens.Color(0xffa3aab4),
    bgActionPrimaryRest = DarkColorTokens.Color(0xffebeef2),
    bgActionSecondaryHovered = DarkColorTokens.Color(0x0ad9c3df),
    bgActionSecondaryPressed = DarkColorTokens.Color(0x0fe9dbf0),
    bgActionSecondaryRest = DarkColorTokens.Color(0xff101317),
    bgCanvasDefault = DarkColorTokens.Color(0xff101317),
    bgCanvasDisabled = DarkColorTokens.Color(0xff181a1f),
    bgCriticalHovered = DarkColorTokens.Color(0xffff665d),
    bgCriticalPrimary = DarkColorTokens.Color(0xfffd3e3c),
    bgCriticalSubtle = DarkColorTokens.Color(0xff3e0000),
    bgCriticalSubtleHovered = DarkColorTokens.Color(0xff470000),
    bgDecorative1 = DarkColorTokens.Color(0xff002600),
    bgDecorative2 = DarkColorTokens.Color(0xff001b4e),
    bgDecorative3 = DarkColorTokens.Color(0xff37004e),
    bgDecorative4 = DarkColorTokens.Color(0xff22006a),
    bgDecorative5 = DarkColorTokens.Color(0xff450018),
    bgDecorative6 = DarkColorTokens.Color(0xff470000),
    bgInfoSubtle = DarkColorTokens.Color(0xff00095d),
    bgSubtlePrimary = DarkColorTokens.Color(0xff26282d),
    bgSubtleSecondary = DarkColorTokens.Color(0xff1d1f24),
    bgSuccessSubtle = DarkColorTokens.Color(0xff001f0e),
    borderCriticalHovered = DarkColorTokens.Color(0xffff665d),
    borderCriticalPrimary = DarkColorTokens.Color(0xfffd3e3c),
    borderCriticalSubtle = DarkColorTokens.Color(0xff710000),
    borderDisabled = DarkColorTokens.Color(0xff323539),
    borderFocused = DarkColorTokens.Color(0xff4187eb),
    borderInfoSubtle = DarkColorTokens.Color(0xff062d80),
    borderInteractiveHovered = DarkColorTokens.Color(0xffa3aab4),
    borderInteractivePrimary = DarkColorTokens.Color(0xff656c76),
    borderInteractiveSecondary = DarkColorTokens.Color(0xff3c3f44),
    borderSuccessSubtle = DarkColorTokens.Color(0xff003d29),
    iconAccentPrimary = DarkColorTokens.Color(0xff129a78),
    iconAccentTertiary = DarkColorTokens.Color(0xff007a62),
    iconCriticalPrimary = DarkColorTokens.Color(0xfffd3e3c),
    iconDisabled = DarkColorTokens.Color(0xff4a4f55),
    iconInfoPrimary = DarkColorTokens.Color(0xff4187eb),
    iconOnSolidPrimary = DarkColorTokens.Color(0xff101317),
    iconPrimary = DarkColorTokens.Color(0xffebeef2),
    iconPrimaryAlpha = DarkColorTokens.Color(0xf2f6f9fe),
    iconQuaternary = DarkColorTokens.Color(0xff4a4f55),
    iconQuaternaryAlpha = DarkColorTokens.Color(0x45e7f1fd),
    iconSecondary = DarkColorTokens.Color(0xff808994),
    iconSecondaryAlpha = DarkColorTokens.Color(0x8ae1effe),
    iconSuccessPrimary = DarkColorTokens.Color(0xff129a78),
    iconTertiary = DarkColorTokens.Color(0xff656c76),
    iconTertiaryAlpha = DarkColorTokens.Color(0x69e0edff),
    textActionAccent = DarkColorTokens.Color(0xff129a78),
    textActionPrimary = DarkColorTokens.Color(0xffebeef2),
    textCriticalPrimary = DarkColorTokens.Color(0xfffd3e3c),
    textDecorative1 = DarkColorTokens.Color(0xff56c02c),
    textDecorative2 = DarkColorTokens.Color(0xff21bacd),
    textDecorative3 = DarkColorTokens.Color(0xffd991de),
    textDecorative4 = DarkColorTokens.Color(0xffad9cfe),
    textDecorative5 = DarkColorTokens.Color(0xfffe84a2),
    textDecorative6 = DarkColorTokens.Color(0xfff6913d),
    textDisabled = DarkColorTokens.Color(0xff656c76),
    textInfoPrimary = DarkColorTokens.Color(0xff4187eb),
    textLinkExternal = DarkColorTokens.Color(0xff4187eb),
    textOnSolidPrimary = DarkColorTokens.Color(0xff101317),
    textPrimary = DarkColorTokens.Color(0xffebeef2),
    textSecondary = DarkColorTokens.Color(0xff808994),
    textSuccessPrimary = DarkColorTokens.Color(0xff129a78),
    isLight = false,
)
