
//
// CompoundUIColorTokens.swift
//

import UIKit

public class CompoundUIColorTokens {
    public static let colorBrandPrimary = #0dbd8b
    public static let colorAlphaPink1400 = UIColor(named: "colorAlphaPink1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink1300 = UIColor(named: "colorAlphaPink1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink1200 = UIColor(named: "colorAlphaPink1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink1100 = UIColor(named: "colorAlphaPink1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink1000 = UIColor(named: "colorAlphaPink1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink900 = UIColor(named: "colorAlphaPink900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink800 = UIColor(named: "colorAlphaPink800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink700 = UIColor(named: "colorAlphaPink700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink600 = UIColor(named: "colorAlphaPink600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink500 = UIColor(named: "colorAlphaPink500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink400 = UIColor(named: "colorAlphaPink400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink300 = UIColor(named: "colorAlphaPink300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink200 = UIColor(named: "colorAlphaPink200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPink100 = UIColor(named: "colorAlphaPink100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia1400 = UIColor(named: "colorAlphaFuchsia1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia1300 = UIColor(named: "colorAlphaFuchsia1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia1200 = UIColor(named: "colorAlphaFuchsia1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia1100 = UIColor(named: "colorAlphaFuchsia1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia1000 = UIColor(named: "colorAlphaFuchsia1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia900 = UIColor(named: "colorAlphaFuchsia900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia800 = UIColor(named: "colorAlphaFuchsia800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia700 = UIColor(named: "colorAlphaFuchsia700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia600 = UIColor(named: "colorAlphaFuchsia600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia500 = UIColor(named: "colorAlphaFuchsia500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia400 = UIColor(named: "colorAlphaFuchsia400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia300 = UIColor(named: "colorAlphaFuchsia300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia200 = UIColor(named: "colorAlphaFuchsia200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaFuchsia100 = UIColor(named: "colorAlphaFuchsia100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple1400 = UIColor(named: "colorAlphaPurple1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple1300 = UIColor(named: "colorAlphaPurple1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple1200 = UIColor(named: "colorAlphaPurple1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple1100 = UIColor(named: "colorAlphaPurple1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple1000 = UIColor(named: "colorAlphaPurple1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple900 = UIColor(named: "colorAlphaPurple900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple800 = UIColor(named: "colorAlphaPurple800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple700 = UIColor(named: "colorAlphaPurple700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple600 = UIColor(named: "colorAlphaPurple600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple500 = UIColor(named: "colorAlphaPurple500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple400 = UIColor(named: "colorAlphaPurple400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple300 = UIColor(named: "colorAlphaPurple300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple200 = UIColor(named: "colorAlphaPurple200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaPurple100 = UIColor(named: "colorAlphaPurple100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue1400 = UIColor(named: "colorAlphaBlue1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue1300 = UIColor(named: "colorAlphaBlue1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue1200 = UIColor(named: "colorAlphaBlue1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue1100 = UIColor(named: "colorAlphaBlue1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue1000 = UIColor(named: "colorAlphaBlue1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue900 = UIColor(named: "colorAlphaBlue900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue800 = UIColor(named: "colorAlphaBlue800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue700 = UIColor(named: "colorAlphaBlue700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue600 = UIColor(named: "colorAlphaBlue600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue500 = UIColor(named: "colorAlphaBlue500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue400 = UIColor(named: "colorAlphaBlue400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue300 = UIColor(named: "colorAlphaBlue300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue200 = UIColor(named: "colorAlphaBlue200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaBlue100 = UIColor(named: "colorAlphaBlue100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan1400 = UIColor(named: "colorAlphaCyan1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan1300 = UIColor(named: "colorAlphaCyan1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan1200 = UIColor(named: "colorAlphaCyan1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan1100 = UIColor(named: "colorAlphaCyan1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan1000 = UIColor(named: "colorAlphaCyan1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan900 = UIColor(named: "colorAlphaCyan900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan800 = UIColor(named: "colorAlphaCyan800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan700 = UIColor(named: "colorAlphaCyan700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan600 = UIColor(named: "colorAlphaCyan600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan500 = UIColor(named: "colorAlphaCyan500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan400 = UIColor(named: "colorAlphaCyan400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan300 = UIColor(named: "colorAlphaCyan300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan200 = UIColor(named: "colorAlphaCyan200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaCyan100 = UIColor(named: "colorAlphaCyan100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen1400 = UIColor(named: "colorAlphaGreen1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen1300 = UIColor(named: "colorAlphaGreen1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen1200 = UIColor(named: "colorAlphaGreen1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen1100 = UIColor(named: "colorAlphaGreen1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen1000 = UIColor(named: "colorAlphaGreen1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen900 = UIColor(named: "colorAlphaGreen900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen800 = UIColor(named: "colorAlphaGreen800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen700 = UIColor(named: "colorAlphaGreen700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen600 = UIColor(named: "colorAlphaGreen600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen500 = UIColor(named: "colorAlphaGreen500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen400 = UIColor(named: "colorAlphaGreen400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen300 = UIColor(named: "colorAlphaGreen300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen200 = UIColor(named: "colorAlphaGreen200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGreen100 = UIColor(named: "colorAlphaGreen100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime1400 = UIColor(named: "colorAlphaLime1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime1300 = UIColor(named: "colorAlphaLime1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime1200 = UIColor(named: "colorAlphaLime1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime1100 = UIColor(named: "colorAlphaLime1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime1000 = UIColor(named: "colorAlphaLime1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime900 = UIColor(named: "colorAlphaLime900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime800 = UIColor(named: "colorAlphaLime800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime700 = UIColor(named: "colorAlphaLime700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime600 = UIColor(named: "colorAlphaLime600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime500 = UIColor(named: "colorAlphaLime500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime400 = UIColor(named: "colorAlphaLime400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime300 = UIColor(named: "colorAlphaLime300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime200 = UIColor(named: "colorAlphaLime200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaLime100 = UIColor(named: "colorAlphaLime100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow1400 = UIColor(named: "colorAlphaYellow1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow1300 = UIColor(named: "colorAlphaYellow1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow1200 = UIColor(named: "colorAlphaYellow1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow1100 = UIColor(named: "colorAlphaYellow1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow1000 = UIColor(named: "colorAlphaYellow1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow900 = UIColor(named: "colorAlphaYellow900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow800 = UIColor(named: "colorAlphaYellow800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow700 = UIColor(named: "colorAlphaYellow700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow600 = UIColor(named: "colorAlphaYellow600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow500 = UIColor(named: "colorAlphaYellow500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow400 = UIColor(named: "colorAlphaYellow400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow300 = UIColor(named: "colorAlphaYellow300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow200 = UIColor(named: "colorAlphaYellow200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaYellow100 = UIColor(named: "colorAlphaYellow100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange1400 = UIColor(named: "colorAlphaOrange1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange1300 = UIColor(named: "colorAlphaOrange1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange1200 = UIColor(named: "colorAlphaOrange1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange1100 = UIColor(named: "colorAlphaOrange1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange1000 = UIColor(named: "colorAlphaOrange1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange900 = UIColor(named: "colorAlphaOrange900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange800 = UIColor(named: "colorAlphaOrange800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange700 = UIColor(named: "colorAlphaOrange700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange600 = UIColor(named: "colorAlphaOrange600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange500 = UIColor(named: "colorAlphaOrange500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange400 = UIColor(named: "colorAlphaOrange400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange300 = UIColor(named: "colorAlphaOrange300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange200 = UIColor(named: "colorAlphaOrange200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaOrange100 = UIColor(named: "colorAlphaOrange100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed1400 = UIColor(named: "colorAlphaRed1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed1300 = UIColor(named: "colorAlphaRed1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed1200 = UIColor(named: "colorAlphaRed1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed1100 = UIColor(named: "colorAlphaRed1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed1000 = UIColor(named: "colorAlphaRed1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed900 = UIColor(named: "colorAlphaRed900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed800 = UIColor(named: "colorAlphaRed800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed700 = UIColor(named: "colorAlphaRed700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed600 = UIColor(named: "colorAlphaRed600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed500 = UIColor(named: "colorAlphaRed500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed400 = UIColor(named: "colorAlphaRed400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed300 = UIColor(named: "colorAlphaRed300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed200 = UIColor(named: "colorAlphaRed200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaRed100 = UIColor(named: "colorAlphaRed100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray1400 = UIColor(named: "colorAlphaGray1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray1300 = UIColor(named: "colorAlphaGray1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray1200 = UIColor(named: "colorAlphaGray1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray1100 = UIColor(named: "colorAlphaGray1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray1000 = UIColor(named: "colorAlphaGray1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray900 = UIColor(named: "colorAlphaGray900", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray800 = UIColor(named: "colorAlphaGray800", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray700 = UIColor(named: "colorAlphaGray700", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray600 = UIColor(named: "colorAlphaGray600", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray500 = UIColor(named: "colorAlphaGray500", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray400 = UIColor(named: "colorAlphaGray400", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray300 = UIColor(named: "colorAlphaGray300", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray200 = UIColor(named: "colorAlphaGray200", in: Bundle.module, compatibleWith: nil)!
    public static let colorAlphaGray100 = UIColor(named: "colorAlphaGray100", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink1400 = UIColor(named: "colorPink1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink1300 = UIColor(named: "colorPink1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink1200 = UIColor(named: "colorPink1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink1100 = UIColor(named: "colorPink1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink1000 = UIColor(named: "colorPink1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink900 = UIColor(named: "colorPink900", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink800 = UIColor(named: "colorPink800", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink700 = UIColor(named: "colorPink700", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink600 = UIColor(named: "colorPink600", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink500 = UIColor(named: "colorPink500", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink400 = UIColor(named: "colorPink400", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink300 = UIColor(named: "colorPink300", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink200 = UIColor(named: "colorPink200", in: Bundle.module, compatibleWith: nil)!
    public static let colorPink100 = UIColor(named: "colorPink100", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia1400 = UIColor(named: "colorFuchsia1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia1300 = UIColor(named: "colorFuchsia1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia1200 = UIColor(named: "colorFuchsia1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia1100 = UIColor(named: "colorFuchsia1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia1000 = UIColor(named: "colorFuchsia1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia900 = UIColor(named: "colorFuchsia900", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia800 = UIColor(named: "colorFuchsia800", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia700 = UIColor(named: "colorFuchsia700", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia600 = UIColor(named: "colorFuchsia600", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia500 = UIColor(named: "colorFuchsia500", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia400 = UIColor(named: "colorFuchsia400", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia300 = UIColor(named: "colorFuchsia300", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia200 = UIColor(named: "colorFuchsia200", in: Bundle.module, compatibleWith: nil)!
    public static let colorFuchsia100 = UIColor(named: "colorFuchsia100", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple1400 = UIColor(named: "colorPurple1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple1300 = UIColor(named: "colorPurple1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple1200 = UIColor(named: "colorPurple1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple1100 = UIColor(named: "colorPurple1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple1000 = UIColor(named: "colorPurple1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple900 = UIColor(named: "colorPurple900", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple800 = UIColor(named: "colorPurple800", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple700 = UIColor(named: "colorPurple700", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple600 = UIColor(named: "colorPurple600", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple500 = UIColor(named: "colorPurple500", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple400 = UIColor(named: "colorPurple400", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple300 = UIColor(named: "colorPurple300", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple200 = UIColor(named: "colorPurple200", in: Bundle.module, compatibleWith: nil)!
    public static let colorPurple100 = UIColor(named: "colorPurple100", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue1400 = UIColor(named: "colorBlue1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue1300 = UIColor(named: "colorBlue1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue1200 = UIColor(named: "colorBlue1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue1100 = UIColor(named: "colorBlue1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue1000 = UIColor(named: "colorBlue1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue900 = UIColor(named: "colorBlue900", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue800 = UIColor(named: "colorBlue800", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue700 = UIColor(named: "colorBlue700", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue600 = UIColor(named: "colorBlue600", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue500 = UIColor(named: "colorBlue500", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue400 = UIColor(named: "colorBlue400", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue300 = UIColor(named: "colorBlue300", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue200 = UIColor(named: "colorBlue200", in: Bundle.module, compatibleWith: nil)!
    public static let colorBlue100 = UIColor(named: "colorBlue100", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan1400 = UIColor(named: "colorCyan1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan1300 = UIColor(named: "colorCyan1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan1200 = UIColor(named: "colorCyan1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan1100 = UIColor(named: "colorCyan1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan1000 = UIColor(named: "colorCyan1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan900 = UIColor(named: "colorCyan900", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan800 = UIColor(named: "colorCyan800", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan700 = UIColor(named: "colorCyan700", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan600 = UIColor(named: "colorCyan600", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan500 = UIColor(named: "colorCyan500", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan400 = UIColor(named: "colorCyan400", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan300 = UIColor(named: "colorCyan300", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan200 = UIColor(named: "colorCyan200", in: Bundle.module, compatibleWith: nil)!
    public static let colorCyan100 = UIColor(named: "colorCyan100", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen1400 = UIColor(named: "colorGreen1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen1300 = UIColor(named: "colorGreen1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen1200 = UIColor(named: "colorGreen1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen1100 = UIColor(named: "colorGreen1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen1000 = UIColor(named: "colorGreen1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen900 = UIColor(named: "colorGreen900", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen800 = UIColor(named: "colorGreen800", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen700 = UIColor(named: "colorGreen700", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen600 = UIColor(named: "colorGreen600", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen500 = UIColor(named: "colorGreen500", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen400 = UIColor(named: "colorGreen400", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen300 = UIColor(named: "colorGreen300", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen200 = UIColor(named: "colorGreen200", in: Bundle.module, compatibleWith: nil)!
    public static let colorGreen100 = UIColor(named: "colorGreen100", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime1400 = UIColor(named: "colorLime1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime1300 = UIColor(named: "colorLime1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime1200 = UIColor(named: "colorLime1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime1100 = UIColor(named: "colorLime1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime1000 = UIColor(named: "colorLime1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime900 = UIColor(named: "colorLime900", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime800 = UIColor(named: "colorLime800", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime700 = UIColor(named: "colorLime700", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime600 = UIColor(named: "colorLime600", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime500 = UIColor(named: "colorLime500", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime400 = UIColor(named: "colorLime400", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime300 = UIColor(named: "colorLime300", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime200 = UIColor(named: "colorLime200", in: Bundle.module, compatibleWith: nil)!
    public static let colorLime100 = UIColor(named: "colorLime100", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow1400 = UIColor(named: "colorYellow1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow1300 = UIColor(named: "colorYellow1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow1200 = UIColor(named: "colorYellow1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow1100 = UIColor(named: "colorYellow1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow1000 = UIColor(named: "colorYellow1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow900 = UIColor(named: "colorYellow900", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow800 = UIColor(named: "colorYellow800", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow700 = UIColor(named: "colorYellow700", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow600 = UIColor(named: "colorYellow600", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow500 = UIColor(named: "colorYellow500", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow400 = UIColor(named: "colorYellow400", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow300 = UIColor(named: "colorYellow300", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow200 = UIColor(named: "colorYellow200", in: Bundle.module, compatibleWith: nil)!
    public static let colorYellow100 = UIColor(named: "colorYellow100", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange1400 = UIColor(named: "colorOrange1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange1300 = UIColor(named: "colorOrange1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange1200 = UIColor(named: "colorOrange1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange1100 = UIColor(named: "colorOrange1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange1000 = UIColor(named: "colorOrange1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange900 = UIColor(named: "colorOrange900", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange800 = UIColor(named: "colorOrange800", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange700 = UIColor(named: "colorOrange700", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange600 = UIColor(named: "colorOrange600", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange500 = UIColor(named: "colorOrange500", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange400 = UIColor(named: "colorOrange400", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange300 = UIColor(named: "colorOrange300", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange200 = UIColor(named: "colorOrange200", in: Bundle.module, compatibleWith: nil)!
    public static let colorOrange100 = UIColor(named: "colorOrange100", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed1400 = UIColor(named: "colorRed1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed1300 = UIColor(named: "colorRed1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed1200 = UIColor(named: "colorRed1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed1100 = UIColor(named: "colorRed1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed1000 = UIColor(named: "colorRed1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed900 = UIColor(named: "colorRed900", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed800 = UIColor(named: "colorRed800", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed700 = UIColor(named: "colorRed700", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed600 = UIColor(named: "colorRed600", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed500 = UIColor(named: "colorRed500", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed400 = UIColor(named: "colorRed400", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed300 = UIColor(named: "colorRed300", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed200 = UIColor(named: "colorRed200", in: Bundle.module, compatibleWith: nil)!
    public static let colorRed100 = UIColor(named: "colorRed100", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray1400 = UIColor(named: "colorGray1400", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray1300 = UIColor(named: "colorGray1300", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray1200 = UIColor(named: "colorGray1200", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray1100 = UIColor(named: "colorGray1100", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray1000 = UIColor(named: "colorGray1000", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray900 = UIColor(named: "colorGray900", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray800 = UIColor(named: "colorGray800", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray700 = UIColor(named: "colorGray700", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray600 = UIColor(named: "colorGray600", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray500 = UIColor(named: "colorGray500", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray400 = UIColor(named: "colorGray400", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray300 = UIColor(named: "colorGray300", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray200 = UIColor(named: "colorGray200", in: Bundle.module, compatibleWith: nil)!
    public static let colorGray100 = UIColor(named: "colorGray100", in: Bundle.module, compatibleWith: nil)!
    public static let colorThemeBg = UIColor(named: "colorThemeBg", in: Bundle.module, compatibleWith: nil)!
    public static let colorIconOnSolidPrimary = colorThemeBg
    public static let colorIconInfoPrimary = colorBlue900
    public static let colorIconSuccessPrimary = colorGreen900
    public static let colorIconCriticalPrimary = colorRed900
    public static let colorIconQuaternaryAlpha = colorAlphaGray700
    public static let colorIconTertiaryAlpha = colorAlphaGray800
    public static let colorIconSecondaryAlpha = colorAlphaGray900
    public static let colorIconPrimaryAlpha = colorAlphaGray1400
    public static let colorIconDisabled = colorGray700
    public static let colorIconQuaternary = colorGray700
    public static let colorIconTertiary = colorGray800
    public static let colorIconSecondary = colorGray900
    public static let colorIconPrimary = colorGray1400
    public static let colorBorderInfoSubtle = colorBlue500
    public static let colorBorderSuccessSubtle = colorGreen500
    public static let colorBorderCriticalSubtle = colorRed500
    public static let colorBorderCriticalHovered = colorRed1000
    public static let colorBorderCriticalPrimary = colorRed900
    public static let colorBorderInteractiveHovered = colorGray1100
    public static let colorBorderInteractiveSecondary = colorGray600
    public static let colorBorderInteractivePrimary = colorGray800
    public static let colorBorderFocused = colorBlue900
    public static let colorBorderDisabled = colorGray500
    public static let colorBgSubtleSecondaryLevel0 = colorThemeBg
    public static let colorBgInfoSubtle = colorBlue200
    public static let colorBgSuccessSubtle = colorGreen200
    public static let colorBgCriticalSubtleHovered = colorRed300
    public static let colorBgCriticalSubtle = colorRed200
    public static let colorBgCriticalHovered = colorRed1000
    public static let colorBgCriticalPrimary = colorRed900
    public static let colorBgActionSecondaryPressed = colorAlphaGray300
    public static let colorBgActionSecondaryHovered = colorAlphaGray200
    public static let colorBgActionSecondaryRest = colorThemeBg
    public static let colorBgActionPrimaryDisabled = colorGray700
    public static let colorBgActionPrimaryPressed = colorGray1100
    public static let colorBgActionPrimaryHovered = colorGray1200
    public static let colorBgActionPrimaryRest = colorGray1400
    public static let colorBgCanvasDefaultLevel1 = colorGray300
    public static let colorBgCanvasDisabled = colorGray200
    public static let colorBgCanvasDefault = colorThemeBg
    public static let colorBgSubtleSecondary = colorGray300
    public static let colorBgSubtlePrimary = colorGray400
    public static let colorTextOnSolidPrimary = colorThemeBg
    public static let colorTextInfoPrimary = colorBlue900
    public static let colorTextSuccessPrimary = colorGreen900
    public static let colorTextCriticalPrimary = colorRed900
    public static let colorTextLinkExternal = colorBlue900
    public static let colorTextActionAccent = colorGreen900
    public static let colorTextActionPrimary = colorGray1400
    public static let colorTextDisabled = colorGray800
    public static let colorTextPlaceholder = colorGray800
    public static let colorTextSecondary = colorGray900
    public static let colorTextPrimary = colorGray1400
    public static let colorAccent1400 = colorGreen1400
    public static let colorAccent1300 = colorGreen1300
    public static let colorAccent1200 = colorGreen1200
    public static let colorAccent1100 = colorGreen1100
    public static let colorAccent1000 = colorGreen1000
    public static let colorAccent900 = colorGreen900
    public static let colorAccent800 = colorGreen800
    public static let colorAccent700 = colorGreen700
    public static let colorAccent600 = colorGreen600
    public static let colorAccent500 = colorGreen500
    public static let colorAccent400 = colorGreen400
    public static let colorAccent300 = colorGreen300
    public static let colorAccent200 = colorGreen200
    public static let colorAccent100 = colorGreen100
    public static let colorIconAccentTertiary = colorAccent800
}
