
//
// CompoundUIColorTokens.swift
//

import UIKit

public class CompoundUIColorTokens {
    public let bgAccentHovered = CompoundCoreUIColorTokens.green1000
    public let bgAccentPressed = CompoundCoreUIColorTokens.green1100
    public let bgAccentRest = CompoundCoreUIColorTokens.green900
    public let bgAccentSelected = CompoundCoreUIColorTokens.alphaGreen300
    public let bgActionPrimaryDisabled = CompoundCoreUIColorTokens.gray700
    public let bgActionPrimaryHovered = CompoundCoreUIColorTokens.gray1200
    public let bgActionPrimaryPressed = CompoundCoreUIColorTokens.gray1100
    public let bgActionPrimaryRest = CompoundCoreUIColorTokens.gray1400
    public let bgActionSecondaryHovered = CompoundCoreUIColorTokens.alphaGray200
    public let bgActionSecondaryPressed = CompoundCoreUIColorTokens.alphaGray300
    public let bgActionSecondaryRest = CompoundCoreUIColorTokens.themeBg
    public let bgActionTertiaryHovered = CompoundCoreUIColorTokens.gray300
    public let bgActionTertiaryRest = CompoundCoreUIColorTokens.themeBg
    public let bgActionTertiarySelected = CompoundCoreUIColorTokens.gray400
    public let bgBadgeAccent = UIColor(named: "bgBadgeAccent", in: Bundle.module, compatibleWith: nil)!
    public let bgBadgeDefault = UIColor(named: "bgBadgeDefault", in: Bundle.module, compatibleWith: nil)!
    public let bgBadgeInfo = UIColor(named: "bgBadgeInfo", in: Bundle.module, compatibleWith: nil)!
    public let bgCanvasDefault = CompoundCoreUIColorTokens.themeBg
    public let bgCanvasDefaultLevel1 = UIColor(named: "bgCanvasDefaultLevel1", in: Bundle.module, compatibleWith: nil)!
    public let bgCanvasDisabled = CompoundCoreUIColorTokens.gray200
    public let bgCriticalHovered = CompoundCoreUIColorTokens.red1000
    public let bgCriticalPrimary = CompoundCoreUIColorTokens.red900
    public let bgCriticalSubtle = CompoundCoreUIColorTokens.red200
    public let bgCriticalSubtleHovered = CompoundCoreUIColorTokens.red300
    public let bgDecorative1 = CompoundCoreUIColorTokens.lime300
    public let bgDecorative2 = CompoundCoreUIColorTokens.cyan300
    public let bgDecorative3 = CompoundCoreUIColorTokens.fuchsia300
    public let bgDecorative4 = CompoundCoreUIColorTokens.purple300
    public let bgDecorative5 = CompoundCoreUIColorTokens.pink300
    public let bgDecorative6 = CompoundCoreUIColorTokens.orange300
    public let bgInfoSubtle = CompoundCoreUIColorTokens.blue200
    public let bgSubtlePrimary = CompoundCoreUIColorTokens.gray400
    public let bgSubtleSecondary = CompoundCoreUIColorTokens.gray300
    public let bgSubtleSecondaryLevel0 = UIColor(named: "bgSubtleSecondaryLevel0", in: Bundle.module, compatibleWith: nil)!
    public let bgSuccessSubtle = CompoundCoreUIColorTokens.green200
    public let borderAccentSubtle = CompoundCoreUIColorTokens.green700
    public let borderCriticalHovered = CompoundCoreUIColorTokens.red1000
    public let borderCriticalPrimary = CompoundCoreUIColorTokens.red900
    public let borderCriticalSubtle = CompoundCoreUIColorTokens.red500
    public let borderDisabled = CompoundCoreUIColorTokens.gray500
    public let borderFocused = CompoundCoreUIColorTokens.blue900
    public let borderInfoSubtle = CompoundCoreUIColorTokens.blue700
    public let borderInteractiveHovered = CompoundCoreUIColorTokens.gray1100
    public let borderInteractivePrimary = CompoundCoreUIColorTokens.gray800
    public let borderInteractiveSecondary = CompoundCoreUIColorTokens.gray600
    public let borderSuccessSubtle = CompoundCoreUIColorTokens.green500
    public let gradientActionStop1 = UIColor(named: "gradientActionStop1", in: Bundle.module, compatibleWith: nil)!
    public let gradientActionStop2 = UIColor(named: "gradientActionStop2", in: Bundle.module, compatibleWith: nil)!
    public let gradientActionStop3 = UIColor(named: "gradientActionStop3", in: Bundle.module, compatibleWith: nil)!
    public let gradientActionStop4 = UIColor(named: "gradientActionStop4", in: Bundle.module, compatibleWith: nil)!
    public let gradientCriticalStop1 = CompoundCoreUIColorTokens.alphaRed500
    public let gradientCriticalStop2 = CompoundCoreUIColorTokens.alphaRed400
    public let gradientCriticalStop3 = CompoundCoreUIColorTokens.alphaRed300
    public let gradientCriticalStop4 = CompoundCoreUIColorTokens.alphaRed200
    public let gradientCriticalStop5 = CompoundCoreUIColorTokens.alphaRed100
    public let gradientCriticalStop6 = CompoundCoreUIColorTokens.transparent
    public let gradientInfoStop1 = CompoundCoreUIColorTokens.alphaBlue500
    public let gradientInfoStop2 = CompoundCoreUIColorTokens.alphaBlue400
    public let gradientInfoStop3 = CompoundCoreUIColorTokens.alphaBlue300
    public let gradientInfoStop4 = CompoundCoreUIColorTokens.alphaBlue200
    public let gradientInfoStop5 = CompoundCoreUIColorTokens.alphaBlue100
    public let gradientInfoStop6 = CompoundCoreUIColorTokens.transparent
    public let gradientSubtleStop1 = CompoundCoreUIColorTokens.alphaGreen500
    public let gradientSubtleStop2 = CompoundCoreUIColorTokens.alphaGreen400
    public let gradientSubtleStop3 = CompoundCoreUIColorTokens.alphaGreen300
    public let gradientSubtleStop4 = CompoundCoreUIColorTokens.alphaGreen200
    public let gradientSubtleStop5 = CompoundCoreUIColorTokens.alphaGreen100
    public let gradientSubtleStop6 = CompoundCoreUIColorTokens.transparent
    public let iconAccentPrimary = CompoundCoreUIColorTokens.green900
    public let iconAccentTertiary = CompoundCoreUIColorTokens.green800
    public let iconCriticalPrimary = CompoundCoreUIColorTokens.red900
    public let iconDisabled = CompoundCoreUIColorTokens.gray700
    public let iconInfoPrimary = CompoundCoreUIColorTokens.blue1100
    public let iconOnSolidPrimary = CompoundCoreUIColorTokens.themeBg
    public let iconPrimary = CompoundCoreUIColorTokens.gray1400
    public let iconPrimaryAlpha = CompoundCoreUIColorTokens.alphaGray1400
    public let iconQuaternary = CompoundCoreUIColorTokens.gray700
    public let iconQuaternaryAlpha = CompoundCoreUIColorTokens.alphaGray700
    public let iconSecondary = CompoundCoreUIColorTokens.gray900
    public let iconSecondaryAlpha = CompoundCoreUIColorTokens.alphaGray900
    public let iconSuccessPrimary = CompoundCoreUIColorTokens.green900
    public let iconTertiary = CompoundCoreUIColorTokens.gray800
    public let iconTertiaryAlpha = CompoundCoreUIColorTokens.alphaGray800
    public let textActionAccent = CompoundCoreUIColorTokens.green900
    public let textActionPrimary = CompoundCoreUIColorTokens.gray1400
    public let textBadgeAccent = CompoundCoreUIColorTokens.green1100
    public let textBadgeInfo = CompoundCoreUIColorTokens.blue1100
    public let textCriticalPrimary = CompoundCoreUIColorTokens.red900
    public let textDecorative1 = CompoundCoreUIColorTokens.lime1100
    public let textDecorative2 = CompoundCoreUIColorTokens.cyan1100
    public let textDecorative3 = CompoundCoreUIColorTokens.fuchsia1100
    public let textDecorative4 = CompoundCoreUIColorTokens.purple1100
    public let textDecorative5 = CompoundCoreUIColorTokens.pink1100
    public let textDecorative6 = CompoundCoreUIColorTokens.orange1100
    public let textDisabled = CompoundCoreUIColorTokens.gray800
    public let textInfoPrimary = CompoundCoreUIColorTokens.blue1100
    public let textLinkExternal = CompoundCoreUIColorTokens.blue1100
    public let textOnSolidPrimary = CompoundCoreUIColorTokens.themeBg
    public let textPrimary = CompoundCoreUIColorTokens.gray1400
    public let textSecondary = CompoundCoreUIColorTokens.gray900
    public let textSuccessPrimary = CompoundCoreUIColorTokens.green900
    public init() { }
}
