
//
// CompoundIconTokens.swift
//

import SwiftUI

public class CompoundIconTokens {
    public static let iconWebBrowser = Image("iconWebBrowser", bundle: Bundle.module) 
    public static let iconVoiceCall = Image("iconVoiceCall", bundle: Bundle.module) 
    public static let iconVisibilityOn = Image("iconVisibilityOn", bundle: Bundle.module) 
    public static let iconVisibilityOff = Image("iconVisibilityOff", bundle: Bundle.module) 
    public static let iconVideoCall = Image("iconVideoCall", bundle: Bundle.module) 
    public static let iconVideoCallOff = Image("iconVideoCallOff", bundle: Bundle.module) 
    public static let iconVideoCallMissed = Image("iconVideoCallMissed", bundle: Bundle.module) 
    public static let iconVideoCallDeclined = Image("iconVideoCallDeclined", bundle: Bundle.module) 
    public static let iconVerified = Image("iconVerified", bundle: Bundle.module) 
    public static let iconUserProfile = Image("iconUserProfile", bundle: Bundle.module) 
    public static let iconUserAdd = Image("iconUserAdd", bundle: Bundle.module) 
    public static let iconUserAddSolid = Image("iconUserAddSolid", bundle: Bundle.module) 
    public static let iconThreads = Image("iconThreads", bundle: Bundle.module) 
    public static let iconThreadsSolid = Image("iconThreadsSolid", bundle: Bundle.module) 
    public static let iconSpotlightView = Image("iconSpotlightView", bundle: Bundle.module) 
    public static let iconShare = Image("iconShare", bundle: Bundle.module) 
    public static let iconShareScreenSolid = Image("iconShareScreenSolid", bundle: Bundle.module) 
    public static let iconShareScreenOutline = Image("iconShareScreenOutline", bundle: Bundle.module) 
    public static let iconShareAndroid = Image("iconShareAndroid", bundle: Bundle.module) 
    public static let iconSettings = Image("iconSettings", bundle: Bundle.module) 
    public static let iconSettingsSolid = Image("iconSettingsSolid", bundle: Bundle.module) 
    public static let iconSearch = Image("iconSearch", bundle: Bundle.module) 
    public static let iconPublic = Image("iconPublic", bundle: Bundle.module) 
    public static let iconPopOut = Image("iconPopOut", bundle: Bundle.module) 
    public static let iconPolls = Image("iconPolls", bundle: Bundle.module) 
    public static let iconOverflowVertical = Image("iconOverflowVertical", bundle: Bundle.module) 
    public static let iconOverflowHorizontal = Image("iconOverflowHorizontal", bundle: Bundle.module) 
    public static let iconOffline = Image("iconOffline", bundle: Bundle.module) 
    public static let iconNotifications = Image("iconNotifications", bundle: Bundle.module) 
    public static let iconNotificationsSolid = Image("iconNotificationsSolid", bundle: Bundle.module) 
    public static let iconNotificationsSolidOff = Image("iconNotificationsSolidOff", bundle: Bundle.module) 
    public static let iconNotificationsOff = Image("iconNotificationsOff", bundle: Bundle.module) 
    public static let iconMobile = Image("iconMobile", bundle: Bundle.module) 
    public static let iconMicOnSolid = Image("iconMicOnSolid", bundle: Bundle.module) 
    public static let iconMicOnOutline = Image("iconMicOnOutline", bundle: Bundle.module) 
    public static let iconMicOffSolid = Image("iconMicOffSolid", bundle: Bundle.module) 
    public static let iconMicOffOutline = Image("iconMicOffOutline", bundle: Bundle.module) 
    public static let iconMention = Image("iconMention", bundle: Bundle.module) 
    public static let iconMarkerReadReceipts = Image("iconMarkerReadReceipts", bundle: Bundle.module) 
    public static let iconLock = Image("iconLock", bundle: Bundle.module) 
    public static let iconLockOff = Image("iconLockOff", bundle: Bundle.module) 
    public static let iconLink = Image("iconLink", bundle: Bundle.module) 
    public static let iconLeave = Image("iconLeave", bundle: Bundle.module) 
    public static let iconInfo = Image("iconInfo", bundle: Bundle.module) 
    public static let iconGridView = Image("iconGridView", bundle: Bundle.module) 
    public static let iconFilter = Image("iconFilter", bundle: Bundle.module) 
    public static let iconFiles = Image("iconFiles", bundle: Bundle.module) 
    public static let iconFavouriteOn = Image("iconFavouriteOn", bundle: Bundle.module) 
    public static let iconFavouriteOff = Image("iconFavouriteOff", bundle: Bundle.module) 
    public static let iconExtensions = Image("iconExtensions", bundle: Bundle.module) 
    public static let iconExportArchive = Image("iconExportArchive", bundle: Bundle.module) 
    public static let iconError = Image("iconError", bundle: Bundle.module) 
    public static let iconEndCall = Image("iconEndCall", bundle: Bundle.module) 
    public static let iconDragList = Image("iconDragList", bundle: Bundle.module) 
    public static let iconDragGrid = Image("iconDragGrid", bundle: Bundle.module) 
    public static let iconDownload = Image("iconDownload", bundle: Bundle.module) 
    public static let iconDelete = Image("iconDelete", bundle: Bundle.module) 
    public static let iconComputer = Image("iconComputer", bundle: Bundle.module) 
    public static let iconClose = Image("iconClose", bundle: Bundle.module) 
    public static let iconChevronUpDown = Image("iconChevronUpDown", bundle: Bundle.module) 
    public static let iconChevronRight = Image("iconChevronRight", bundle: Bundle.module) 
    public static let iconChevronLeft = Image("iconChevronLeft", bundle: Bundle.module) 
    public static let iconChevronDown = Image("iconChevronDown", bundle: Bundle.module) 
    public static let iconCheck = Image("iconCheck", bundle: Bundle.module) 
    public static let iconCheckCircle = Image("iconCheckCircle", bundle: Bundle.module) 
    public static let iconChat = Image("iconChat", bundle: Bundle.module) 
    public static let iconChatProblem = Image("iconChatProblem", bundle: Bundle.module) 
    public static let iconChatNew = Image("iconChatNew", bundle: Bundle.module) 
    public static let iconBlock = Image("iconBlock", bundle: Bundle.module) 
    public static let iconArrowUpRight = Image("iconArrowUpRight", bundle: Bundle.module) 
    public static let iconArrowRight = Image("iconArrowRight", bundle: Bundle.module) 
    public static let iconArrowLeft = Image("iconArrowLeft", bundle: Bundle.module) 
}
