
//
// CompoundLightHcDesignTokens.swift
//

import SwiftUI

public class CompoundLightHcDesignTokens {
    public static let iconThread = Image("iconThread", bundle: Bundle.module) 
    public static let colorAlphaPink1400 = Color("colorAlphaPink1400", bundle: Bundle.module) 
    public static let colorAlphaPink1300 = Color("colorAlphaPink1300", bundle: Bundle.module) 
    public static let colorAlphaPink1200 = Color("colorAlphaPink1200", bundle: Bundle.module) 
    public static let colorAlphaPink1100 = Color("colorAlphaPink1100", bundle: Bundle.module) 
    public static let colorAlphaPink1000 = Color("colorAlphaPink1000", bundle: Bundle.module) 
    public static let colorAlphaPink900 = Color("colorAlphaPink900", bundle: Bundle.module) 
    public static let colorAlphaPink800 = Color("colorAlphaPink800", bundle: Bundle.module) 
    public static let colorAlphaPink700 = Color("colorAlphaPink700", bundle: Bundle.module) 
    public static let colorAlphaPink600 = Color("colorAlphaPink600", bundle: Bundle.module) 
    public static let colorAlphaPink500 = Color("colorAlphaPink500", bundle: Bundle.module) 
    public static let colorAlphaPink400 = Color("colorAlphaPink400", bundle: Bundle.module) 
    public static let colorAlphaPink300 = Color("colorAlphaPink300", bundle: Bundle.module) 
    public static let colorAlphaPink200 = Color("colorAlphaPink200", bundle: Bundle.module) 
    public static let colorAlphaPink100 = Color("colorAlphaPink100", bundle: Bundle.module) 
    public static let colorAlphaFuchsia1400 = Color("colorAlphaFuchsia1400", bundle: Bundle.module) 
    public static let colorAlphaFuchsia1300 = Color("colorAlphaFuchsia1300", bundle: Bundle.module) 
    public static let colorAlphaFuchsia1200 = Color("colorAlphaFuchsia1200", bundle: Bundle.module) 
    public static let colorAlphaFuchsia1100 = Color("colorAlphaFuchsia1100", bundle: Bundle.module) 
    public static let colorAlphaFuchsia1000 = Color("colorAlphaFuchsia1000", bundle: Bundle.module) 
    public static let colorAlphaFuchsia900 = Color("colorAlphaFuchsia900", bundle: Bundle.module) 
    public static let colorAlphaFuchsia800 = Color("colorAlphaFuchsia800", bundle: Bundle.module) 
    public static let colorAlphaFuchsia700 = Color("colorAlphaFuchsia700", bundle: Bundle.module) 
    public static let colorAlphaFuchsia600 = Color("colorAlphaFuchsia600", bundle: Bundle.module) 
    public static let colorAlphaFuchsia500 = Color("colorAlphaFuchsia500", bundle: Bundle.module) 
    public static let colorAlphaFuchsia400 = Color("colorAlphaFuchsia400", bundle: Bundle.module) 
    public static let colorAlphaFuchsia300 = Color("colorAlphaFuchsia300", bundle: Bundle.module) 
    public static let colorAlphaFuchsia200 = Color("colorAlphaFuchsia200", bundle: Bundle.module) 
    public static let colorAlphaFuchsia100 = Color("colorAlphaFuchsia100", bundle: Bundle.module) 
    public static let colorAlphaPurple1400 = Color("colorAlphaPurple1400", bundle: Bundle.module) 
    public static let colorAlphaPurple1300 = Color("colorAlphaPurple1300", bundle: Bundle.module) 
    public static let colorAlphaPurple1200 = Color("colorAlphaPurple1200", bundle: Bundle.module) 
    public static let colorAlphaPurple1100 = Color("colorAlphaPurple1100", bundle: Bundle.module) 
    public static let colorAlphaPurple1000 = Color("colorAlphaPurple1000", bundle: Bundle.module) 
    public static let colorAlphaPurple900 = Color("colorAlphaPurple900", bundle: Bundle.module) 
    public static let colorAlphaPurple800 = Color("colorAlphaPurple800", bundle: Bundle.module) 
    public static let colorAlphaPurple700 = Color("colorAlphaPurple700", bundle: Bundle.module) 
    public static let colorAlphaPurple600 = Color("colorAlphaPurple600", bundle: Bundle.module) 
    public static let colorAlphaPurple500 = Color("colorAlphaPurple500", bundle: Bundle.module) 
    public static let colorAlphaPurple400 = Color("colorAlphaPurple400", bundle: Bundle.module) 
    public static let colorAlphaPurple300 = Color("colorAlphaPurple300", bundle: Bundle.module) 
    public static let colorAlphaPurple200 = Color("colorAlphaPurple200", bundle: Bundle.module) 
    public static let colorAlphaPurple100 = Color("colorAlphaPurple100", bundle: Bundle.module) 
    public static let colorAlphaBlue1400 = Color("colorAlphaBlue1400", bundle: Bundle.module) 
    public static let colorAlphaBlue1300 = Color("colorAlphaBlue1300", bundle: Bundle.module) 
    public static let colorAlphaBlue1200 = Color("colorAlphaBlue1200", bundle: Bundle.module) 
    public static let colorAlphaBlue1100 = Color("colorAlphaBlue1100", bundle: Bundle.module) 
    public static let colorAlphaBlue1000 = Color("colorAlphaBlue1000", bundle: Bundle.module) 
    public static let colorAlphaBlue900 = Color("colorAlphaBlue900", bundle: Bundle.module) 
    public static let colorAlphaBlue800 = Color("colorAlphaBlue800", bundle: Bundle.module) 
    public static let colorAlphaBlue700 = Color("colorAlphaBlue700", bundle: Bundle.module) 
    public static let colorAlphaBlue600 = Color("colorAlphaBlue600", bundle: Bundle.module) 
    public static let colorAlphaBlue500 = Color("colorAlphaBlue500", bundle: Bundle.module) 
    public static let colorAlphaBlue400 = Color("colorAlphaBlue400", bundle: Bundle.module) 
    public static let colorAlphaBlue300 = Color("colorAlphaBlue300", bundle: Bundle.module) 
    public static let colorAlphaBlue200 = Color("colorAlphaBlue200", bundle: Bundle.module) 
    public static let colorAlphaBlue100 = Color("colorAlphaBlue100", bundle: Bundle.module) 
    public static let colorAlphaCyan1400 = Color("colorAlphaCyan1400", bundle: Bundle.module) 
    public static let colorAlphaCyan1300 = Color("colorAlphaCyan1300", bundle: Bundle.module) 
    public static let colorAlphaCyan1200 = Color("colorAlphaCyan1200", bundle: Bundle.module) 
    public static let colorAlphaCyan1100 = Color("colorAlphaCyan1100", bundle: Bundle.module) 
    public static let colorAlphaCyan1000 = Color("colorAlphaCyan1000", bundle: Bundle.module) 
    public static let colorAlphaCyan900 = Color("colorAlphaCyan900", bundle: Bundle.module) 
    public static let colorAlphaCyan800 = Color("colorAlphaCyan800", bundle: Bundle.module) 
    public static let colorAlphaCyan700 = Color("colorAlphaCyan700", bundle: Bundle.module) 
    public static let colorAlphaCyan600 = Color("colorAlphaCyan600", bundle: Bundle.module) 
    public static let colorAlphaCyan500 = Color("colorAlphaCyan500", bundle: Bundle.module) 
    public static let colorAlphaCyan400 = Color("colorAlphaCyan400", bundle: Bundle.module) 
    public static let colorAlphaCyan300 = Color("colorAlphaCyan300", bundle: Bundle.module) 
    public static let colorAlphaCyan200 = Color("colorAlphaCyan200", bundle: Bundle.module) 
    public static let colorAlphaCyan100 = Color("colorAlphaCyan100", bundle: Bundle.module) 
    public static let colorAlphaGreen1400 = Color("colorAlphaGreen1400", bundle: Bundle.module) 
    public static let colorAlphaGreen1300 = Color("colorAlphaGreen1300", bundle: Bundle.module) 
    public static let colorAlphaGreen1200 = Color("colorAlphaGreen1200", bundle: Bundle.module) 
    public static let colorAlphaGreen1100 = Color("colorAlphaGreen1100", bundle: Bundle.module) 
    public static let colorAlphaGreen1000 = Color("colorAlphaGreen1000", bundle: Bundle.module) 
    public static let colorAlphaGreen900 = Color("colorAlphaGreen900", bundle: Bundle.module) 
    public static let colorAlphaGreen800 = Color("colorAlphaGreen800", bundle: Bundle.module) 
    public static let colorAlphaGreen700 = Color("colorAlphaGreen700", bundle: Bundle.module) 
    public static let colorAlphaGreen600 = Color("colorAlphaGreen600", bundle: Bundle.module) 
    public static let colorAlphaGreen500 = Color("colorAlphaGreen500", bundle: Bundle.module) 
    public static let colorAlphaGreen400 = Color("colorAlphaGreen400", bundle: Bundle.module) 
    public static let colorAlphaGreen300 = Color("colorAlphaGreen300", bundle: Bundle.module) 
    public static let colorAlphaGreen200 = Color("colorAlphaGreen200", bundle: Bundle.module) 
    public static let colorAlphaGreen100 = Color("colorAlphaGreen100", bundle: Bundle.module) 
    public static let colorAlphaLime1400 = Color("colorAlphaLime1400", bundle: Bundle.module) 
    public static let colorAlphaLime1300 = Color("colorAlphaLime1300", bundle: Bundle.module) 
    public static let colorAlphaLime1200 = Color("colorAlphaLime1200", bundle: Bundle.module) 
    public static let colorAlphaLime1100 = Color("colorAlphaLime1100", bundle: Bundle.module) 
    public static let colorAlphaLime1000 = Color("colorAlphaLime1000", bundle: Bundle.module) 
    public static let colorAlphaLime900 = Color("colorAlphaLime900", bundle: Bundle.module) 
    public static let colorAlphaLime800 = Color("colorAlphaLime800", bundle: Bundle.module) 
    public static let colorAlphaLime700 = Color("colorAlphaLime700", bundle: Bundle.module) 
    public static let colorAlphaLime600 = Color("colorAlphaLime600", bundle: Bundle.module) 
    public static let colorAlphaLime500 = Color("colorAlphaLime500", bundle: Bundle.module) 
    public static let colorAlphaLime400 = Color("colorAlphaLime400", bundle: Bundle.module) 
    public static let colorAlphaLime300 = Color("colorAlphaLime300", bundle: Bundle.module) 
    public static let colorAlphaLime200 = Color("colorAlphaLime200", bundle: Bundle.module) 
    public static let colorAlphaLime100 = Color("colorAlphaLime100", bundle: Bundle.module) 
    public static let colorAlphaYellow1400 = Color("colorAlphaYellow1400", bundle: Bundle.module) 
    public static let colorAlphaYellow1300 = Color("colorAlphaYellow1300", bundle: Bundle.module) 
    public static let colorAlphaYellow1200 = Color("colorAlphaYellow1200", bundle: Bundle.module) 
    public static let colorAlphaYellow1100 = Color("colorAlphaYellow1100", bundle: Bundle.module) 
    public static let colorAlphaYellow1000 = Color("colorAlphaYellow1000", bundle: Bundle.module) 
    public static let colorAlphaYellow900 = Color("colorAlphaYellow900", bundle: Bundle.module) 
    public static let colorAlphaYellow800 = Color("colorAlphaYellow800", bundle: Bundle.module) 
    public static let colorAlphaYellow700 = Color("colorAlphaYellow700", bundle: Bundle.module) 
    public static let colorAlphaYellow600 = Color("colorAlphaYellow600", bundle: Bundle.module) 
    public static let colorAlphaYellow500 = Color("colorAlphaYellow500", bundle: Bundle.module) 
    public static let colorAlphaYellow400 = Color("colorAlphaYellow400", bundle: Bundle.module) 
    public static let colorAlphaYellow300 = Color("colorAlphaYellow300", bundle: Bundle.module) 
    public static let colorAlphaYellow200 = Color("colorAlphaYellow200", bundle: Bundle.module) 
    public static let colorAlphaYellow100 = Color("colorAlphaYellow100", bundle: Bundle.module) 
    public static let colorAlphaOrange1400 = Color("colorAlphaOrange1400", bundle: Bundle.module) 
    public static let colorAlphaOrange1300 = Color("colorAlphaOrange1300", bundle: Bundle.module) 
    public static let colorAlphaOrange1200 = Color("colorAlphaOrange1200", bundle: Bundle.module) 
    public static let colorAlphaOrange1100 = Color("colorAlphaOrange1100", bundle: Bundle.module) 
    public static let colorAlphaOrange1000 = Color("colorAlphaOrange1000", bundle: Bundle.module) 
    public static let colorAlphaOrange900 = Color("colorAlphaOrange900", bundle: Bundle.module) 
    public static let colorAlphaOrange800 = Color("colorAlphaOrange800", bundle: Bundle.module) 
    public static let colorAlphaOrange700 = Color("colorAlphaOrange700", bundle: Bundle.module) 
    public static let colorAlphaOrange600 = Color("colorAlphaOrange600", bundle: Bundle.module) 
    public static let colorAlphaOrange500 = Color("colorAlphaOrange500", bundle: Bundle.module) 
    public static let colorAlphaOrange400 = Color("colorAlphaOrange400", bundle: Bundle.module) 
    public static let colorAlphaOrange300 = Color("colorAlphaOrange300", bundle: Bundle.module) 
    public static let colorAlphaOrange200 = Color("colorAlphaOrange200", bundle: Bundle.module) 
    public static let colorAlphaOrange100 = Color("colorAlphaOrange100", bundle: Bundle.module) 
    public static let colorAlphaRed1400 = Color("colorAlphaRed1400", bundle: Bundle.module) 
    public static let colorAlphaRed1300 = Color("colorAlphaRed1300", bundle: Bundle.module) 
    public static let colorAlphaRed1200 = Color("colorAlphaRed1200", bundle: Bundle.module) 
    public static let colorAlphaRed1100 = Color("colorAlphaRed1100", bundle: Bundle.module) 
    public static let colorAlphaRed1000 = Color("colorAlphaRed1000", bundle: Bundle.module) 
    public static let colorAlphaRed900 = Color("colorAlphaRed900", bundle: Bundle.module) 
    public static let colorAlphaRed800 = Color("colorAlphaRed800", bundle: Bundle.module) 
    public static let colorAlphaRed700 = Color("colorAlphaRed700", bundle: Bundle.module) 
    public static let colorAlphaRed600 = Color("colorAlphaRed600", bundle: Bundle.module) 
    public static let colorAlphaRed500 = Color("colorAlphaRed500", bundle: Bundle.module) 
    public static let colorAlphaRed400 = Color("colorAlphaRed400", bundle: Bundle.module) 
    public static let colorAlphaRed300 = Color("colorAlphaRed300", bundle: Bundle.module) 
    public static let colorAlphaRed200 = Color("colorAlphaRed200", bundle: Bundle.module) 
    public static let colorAlphaRed100 = Color("colorAlphaRed100", bundle: Bundle.module) 
    public static let colorAlphaGray1400 = Color("colorAlphaGray1400", bundle: Bundle.module) 
    public static let colorAlphaGray1300 = Color("colorAlphaGray1300", bundle: Bundle.module) 
    public static let colorAlphaGray1200 = Color("colorAlphaGray1200", bundle: Bundle.module) 
    public static let colorAlphaGray1100 = Color("colorAlphaGray1100", bundle: Bundle.module) 
    public static let colorAlphaGray1000 = Color("colorAlphaGray1000", bundle: Bundle.module) 
    public static let colorAlphaGray900 = Color("colorAlphaGray900", bundle: Bundle.module) 
    public static let colorAlphaGray800 = Color("colorAlphaGray800", bundle: Bundle.module) 
    public static let colorAlphaGray700 = Color("colorAlphaGray700", bundle: Bundle.module) 
    public static let colorAlphaGray600 = Color("colorAlphaGray600", bundle: Bundle.module) 
    public static let colorAlphaGray500 = Color("colorAlphaGray500", bundle: Bundle.module) 
    public static let colorAlphaGray400 = Color("colorAlphaGray400", bundle: Bundle.module) 
    public static let colorAlphaGray300 = Color("colorAlphaGray300", bundle: Bundle.module) 
    public static let colorAlphaGray200 = Color("colorAlphaGray200", bundle: Bundle.module) 
    public static let colorAlphaGray100 = Color("colorAlphaGray100", bundle: Bundle.module) 
    public static let colorPink1400 = Color("colorPink1400", bundle: Bundle.module) 
    public static let colorPink1300 = Color("colorPink1300", bundle: Bundle.module) 
    public static let colorPink1200 = Color("colorPink1200", bundle: Bundle.module) 
    public static let colorPink1100 = Color("colorPink1100", bundle: Bundle.module) 
    public static let colorPink1000 = Color("colorPink1000", bundle: Bundle.module) 
    public static let colorPink900 = Color("colorPink900", bundle: Bundle.module) 
    public static let colorPink800 = Color("colorPink800", bundle: Bundle.module) 
    public static let colorPink700 = Color("colorPink700", bundle: Bundle.module) 
    public static let colorPink600 = Color("colorPink600", bundle: Bundle.module) 
    public static let colorPink500 = Color("colorPink500", bundle: Bundle.module) 
    public static let colorPink400 = Color("colorPink400", bundle: Bundle.module) 
    public static let colorPink300 = Color("colorPink300", bundle: Bundle.module) 
    public static let colorPink200 = Color("colorPink200", bundle: Bundle.module) 
    public static let colorPink100 = Color("colorPink100", bundle: Bundle.module) 
    public static let colorFuchsia1400 = Color("colorFuchsia1400", bundle: Bundle.module) 
    public static let colorFuchsia1300 = Color("colorFuchsia1300", bundle: Bundle.module) 
    public static let colorFuchsia1200 = Color("colorFuchsia1200", bundle: Bundle.module) 
    public static let colorFuchsia1100 = Color("colorFuchsia1100", bundle: Bundle.module) 
    public static let colorFuchsia1000 = Color("colorFuchsia1000", bundle: Bundle.module) 
    public static let colorFuchsia900 = Color("colorFuchsia900", bundle: Bundle.module) 
    public static let colorFuchsia800 = Color("colorFuchsia800", bundle: Bundle.module) 
    public static let colorFuchsia700 = Color("colorFuchsia700", bundle: Bundle.module) 
    public static let colorFuchsia600 = Color("colorFuchsia600", bundle: Bundle.module) 
    public static let colorFuchsia500 = Color("colorFuchsia500", bundle: Bundle.module) 
    public static let colorFuchsia400 = Color("colorFuchsia400", bundle: Bundle.module) 
    public static let colorFuchsia300 = Color("colorFuchsia300", bundle: Bundle.module) 
    public static let colorFuchsia200 = Color("colorFuchsia200", bundle: Bundle.module) 
    public static let colorFuchsia100 = Color("colorFuchsia100", bundle: Bundle.module) 
    public static let colorPurple1400 = Color("colorPurple1400", bundle: Bundle.module) 
    public static let colorPurple1300 = Color("colorPurple1300", bundle: Bundle.module) 
    public static let colorPurple1200 = Color("colorPurple1200", bundle: Bundle.module) 
    public static let colorPurple1100 = Color("colorPurple1100", bundle: Bundle.module) 
    public static let colorPurple1000 = Color("colorPurple1000", bundle: Bundle.module) 
    public static let colorPurple900 = Color("colorPurple900", bundle: Bundle.module) 
    public static let colorPurple800 = Color("colorPurple800", bundle: Bundle.module) 
    public static let colorPurple700 = Color("colorPurple700", bundle: Bundle.module) 
    public static let colorPurple600 = Color("colorPurple600", bundle: Bundle.module) 
    public static let colorPurple500 = Color("colorPurple500", bundle: Bundle.module) 
    public static let colorPurple400 = Color("colorPurple400", bundle: Bundle.module) 
    public static let colorPurple300 = Color("colorPurple300", bundle: Bundle.module) 
    public static let colorPurple200 = Color("colorPurple200", bundle: Bundle.module) 
    public static let colorPurple100 = Color("colorPurple100", bundle: Bundle.module) 
    public static let colorBlue1400 = Color("colorBlue1400", bundle: Bundle.module) 
    public static let colorBlue1300 = Color("colorBlue1300", bundle: Bundle.module) 
    public static let colorBlue1200 = Color("colorBlue1200", bundle: Bundle.module) 
    public static let colorBlue1100 = Color("colorBlue1100", bundle: Bundle.module) 
    public static let colorBlue1000 = Color("colorBlue1000", bundle: Bundle.module) 
    public static let colorBlue900 = Color("colorBlue900", bundle: Bundle.module) 
    public static let colorBlue800 = Color("colorBlue800", bundle: Bundle.module) 
    public static let colorBlue700 = Color("colorBlue700", bundle: Bundle.module) 
    public static let colorBlue600 = Color("colorBlue600", bundle: Bundle.module) 
    public static let colorBlue500 = Color("colorBlue500", bundle: Bundle.module) 
    public static let colorBlue400 = Color("colorBlue400", bundle: Bundle.module) 
    public static let colorBlue300 = Color("colorBlue300", bundle: Bundle.module) 
    public static let colorBlue200 = Color("colorBlue200", bundle: Bundle.module) 
    public static let colorBlue100 = Color("colorBlue100", bundle: Bundle.module) 
    public static let colorCyan1400 = Color("colorCyan1400", bundle: Bundle.module) 
    public static let colorCyan1300 = Color("colorCyan1300", bundle: Bundle.module) 
    public static let colorCyan1200 = Color("colorCyan1200", bundle: Bundle.module) 
    public static let colorCyan1100 = Color("colorCyan1100", bundle: Bundle.module) 
    public static let colorCyan1000 = Color("colorCyan1000", bundle: Bundle.module) 
    public static let colorCyan900 = Color("colorCyan900", bundle: Bundle.module) 
    public static let colorCyan800 = Color("colorCyan800", bundle: Bundle.module) 
    public static let colorCyan700 = Color("colorCyan700", bundle: Bundle.module) 
    public static let colorCyan600 = Color("colorCyan600", bundle: Bundle.module) 
    public static let colorCyan500 = Color("colorCyan500", bundle: Bundle.module) 
    public static let colorCyan400 = Color("colorCyan400", bundle: Bundle.module) 
    public static let colorCyan300 = Color("colorCyan300", bundle: Bundle.module) 
    public static let colorCyan200 = Color("colorCyan200", bundle: Bundle.module) 
    public static let colorCyan100 = Color("colorCyan100", bundle: Bundle.module) 
    public static let colorGreen1400 = Color("colorGreen1400", bundle: Bundle.module) 
    public static let colorGreen1300 = Color("colorGreen1300", bundle: Bundle.module) 
    public static let colorGreen1200 = Color("colorGreen1200", bundle: Bundle.module) 
    public static let colorGreen1100 = Color("colorGreen1100", bundle: Bundle.module) 
    public static let colorGreen1000 = Color("colorGreen1000", bundle: Bundle.module) 
    public static let colorGreen900 = Color("colorGreen900", bundle: Bundle.module) 
    public static let colorGreen800 = Color("colorGreen800", bundle: Bundle.module) 
    public static let colorGreen700 = Color("colorGreen700", bundle: Bundle.module) 
    public static let colorGreen600 = Color("colorGreen600", bundle: Bundle.module) 
    public static let colorGreen500 = Color("colorGreen500", bundle: Bundle.module) 
    public static let colorGreen400 = Color("colorGreen400", bundle: Bundle.module) 
    public static let colorGreen300 = Color("colorGreen300", bundle: Bundle.module) 
    public static let colorGreen200 = Color("colorGreen200", bundle: Bundle.module) 
    public static let colorGreen100 = Color("colorGreen100", bundle: Bundle.module) 
    public static let colorLime1400 = Color("colorLime1400", bundle: Bundle.module) 
    public static let colorLime1300 = Color("colorLime1300", bundle: Bundle.module) 
    public static let colorLime1200 = Color("colorLime1200", bundle: Bundle.module) 
    public static let colorLime1100 = Color("colorLime1100", bundle: Bundle.module) 
    public static let colorLime1000 = Color("colorLime1000", bundle: Bundle.module) 
    public static let colorLime900 = Color("colorLime900", bundle: Bundle.module) 
    public static let colorLime800 = Color("colorLime800", bundle: Bundle.module) 
    public static let colorLime700 = Color("colorLime700", bundle: Bundle.module) 
    public static let colorLime600 = Color("colorLime600", bundle: Bundle.module) 
    public static let colorLime500 = Color("colorLime500", bundle: Bundle.module) 
    public static let colorLime400 = Color("colorLime400", bundle: Bundle.module) 
    public static let colorLime300 = Color("colorLime300", bundle: Bundle.module) 
    public static let colorLime200 = Color("colorLime200", bundle: Bundle.module) 
    public static let colorLime100 = Color("colorLime100", bundle: Bundle.module) 
    public static let colorYellow1400 = Color("colorYellow1400", bundle: Bundle.module) 
    public static let colorYellow1300 = Color("colorYellow1300", bundle: Bundle.module) 
    public static let colorYellow1200 = Color("colorYellow1200", bundle: Bundle.module) 
    public static let colorYellow1100 = Color("colorYellow1100", bundle: Bundle.module) 
    public static let colorYellow1000 = Color("colorYellow1000", bundle: Bundle.module) 
    public static let colorYellow900 = Color("colorYellow900", bundle: Bundle.module) 
    public static let colorYellow800 = Color("colorYellow800", bundle: Bundle.module) 
    public static let colorYellow700 = Color("colorYellow700", bundle: Bundle.module) 
    public static let colorYellow600 = Color("colorYellow600", bundle: Bundle.module) 
    public static let colorYellow500 = Color("colorYellow500", bundle: Bundle.module) 
    public static let colorYellow400 = Color("colorYellow400", bundle: Bundle.module) 
    public static let colorYellow300 = Color("colorYellow300", bundle: Bundle.module) 
    public static let colorYellow200 = Color("colorYellow200", bundle: Bundle.module) 
    public static let colorYellow100 = Color("colorYellow100", bundle: Bundle.module) 
    public static let colorOrange1400 = Color("colorOrange1400", bundle: Bundle.module) 
    public static let colorOrange1300 = Color("colorOrange1300", bundle: Bundle.module) 
    public static let colorOrange1200 = Color("colorOrange1200", bundle: Bundle.module) 
    public static let colorOrange1100 = Color("colorOrange1100", bundle: Bundle.module) 
    public static let colorOrange1000 = Color("colorOrange1000", bundle: Bundle.module) 
    public static let colorOrange900 = Color("colorOrange900", bundle: Bundle.module) 
    public static let colorOrange800 = Color("colorOrange800", bundle: Bundle.module) 
    public static let colorOrange700 = Color("colorOrange700", bundle: Bundle.module) 
    public static let colorOrange600 = Color("colorOrange600", bundle: Bundle.module) 
    public static let colorOrange500 = Color("colorOrange500", bundle: Bundle.module) 
    public static let colorOrange400 = Color("colorOrange400", bundle: Bundle.module) 
    public static let colorOrange300 = Color("colorOrange300", bundle: Bundle.module) 
    public static let colorOrange200 = Color("colorOrange200", bundle: Bundle.module) 
    public static let colorOrange100 = Color("colorOrange100", bundle: Bundle.module) 
    public static let colorRed1400 = Color("colorRed1400", bundle: Bundle.module) 
    public static let colorRed1300 = Color("colorRed1300", bundle: Bundle.module) 
    public static let colorRed1200 = Color("colorRed1200", bundle: Bundle.module) 
    public static let colorRed1100 = Color("colorRed1100", bundle: Bundle.module) 
    public static let colorRed1000 = Color("colorRed1000", bundle: Bundle.module) 
    public static let colorRed900 = Color("colorRed900", bundle: Bundle.module) 
    public static let colorRed800 = Color("colorRed800", bundle: Bundle.module) 
    public static let colorRed700 = Color("colorRed700", bundle: Bundle.module) 
    public static let colorRed600 = Color("colorRed600", bundle: Bundle.module) 
    public static let colorRed500 = Color("colorRed500", bundle: Bundle.module) 
    public static let colorRed400 = Color("colorRed400", bundle: Bundle.module) 
    public static let colorRed300 = Color("colorRed300", bundle: Bundle.module) 
    public static let colorRed200 = Color("colorRed200", bundle: Bundle.module) 
    public static let colorRed100 = Color("colorRed100", bundle: Bundle.module) 
    public static let colorGray1400 = Color("colorGray1400", bundle: Bundle.module) 
    public static let colorGray1300 = Color("colorGray1300", bundle: Bundle.module) 
    public static let colorGray1200 = Color("colorGray1200", bundle: Bundle.module) 
    public static let colorGray1100 = Color("colorGray1100", bundle: Bundle.module) 
    public static let colorGray1000 = Color("colorGray1000", bundle: Bundle.module) 
    public static let colorGray900 = Color("colorGray900", bundle: Bundle.module) 
    public static let colorGray800 = Color("colorGray800", bundle: Bundle.module) 
    public static let colorGray700 = Color("colorGray700", bundle: Bundle.module) 
    public static let colorGray600 = Color("colorGray600", bundle: Bundle.module) 
    public static let colorGray500 = Color("colorGray500", bundle: Bundle.module) 
    public static let colorGray400 = Color("colorGray400", bundle: Bundle.module) 
    public static let colorGray300 = Color("colorGray300", bundle: Bundle.module) 
    public static let colorGray200 = Color("colorGray200", bundle: Bundle.module) 
    public static let colorGray100 = Color("colorGray100", bundle: Bundle.module) 
    public static let colorThemeBg = Color("colorThemeBg", bundle: Bundle.module) 
    public static let fontSizeHeadingXl = CGFloat(34)
    public static let fontSizeHeadingLg = CGFloat(28)
    public static let fontSizeHeadingMd = CGFloat(22)
    public static let fontSizeHeadingSm = CGFloat(20)
    public static let fontSizeBodyLg = CGFloat(17)
    public static let fontSizeBodyMd = CGFloat(15)
    public static let fontSizeBodySm = CGFloat(13)
    public static let fontSizeBodyXs = CGFloat(12)
    public static let fontLineHeightHeadingXlRegular = CGFloat(41)
    public static let fontLineHeightHeadingLgRegular = CGFloat(34)
    public static let fontLineHeightHeadingMdRegular = CGFloat(28)
    public static let fontLineHeightHeadingSmRegular = CGFloat(25)
    public static let fontLineHeightBodyLgRegular = CGFloat(22)
    public static let fontLineHeightBodyMdRegular = CGFloat(20)
    public static let fontLineHeightBodySmRegular = CGFloat(18)
    public static let fontLineHeightBodyXsRegular = CGFloat(16)
    public static let fontWeightBold = Font.Weight.regular
    public static let fontWeightSemibold = Font.Weight.regular
    public static let fontWeightRegular = Font.Weight.regular
    public static let fontFamilyMono = "SF Mono"
    public static let fontFamilySans = "SF Pro"
    public static let borderWidth0_5 = CGFloat(0.5)
    public static let borderWidth4 = CGFloat(4)
    public static let borderWidth2 = CGFloat(2)
    public static let borderWidth1 = CGFloat(1)
    public static let space56X = CGFloat(224)
    public static let space36X = CGFloat(144)
    public static let space16X = CGFloat(64)
    public static let space12X = CGFloat(48)
    public static let space11X = CGFloat(44)
    public static let space10X = CGFloat(40)
    public static let space6X = CGFloat(24)
    public static let space0X = CGFloat(0)
    public static let spaceScale = CGFloat(4)
    public static let colorIconOnSolidPrimary = colorThemeBg
    public static let colorIconInfoPrimary = colorBlue900
    public static let colorIconSuccessPrimary = colorGreen900
    public static let colorIconCriticalPrimary = colorRed900
    public static let colorIconAccentTertiary = colorGreen800
    public static let colorIconQuaternaryAlpha = colorAlphaGray700
    public static let colorIconTertiaryAlpha = colorAlphaGray800
    public static let colorIconSecondaryAlpha = colorAlphaGray900
    public static let colorIconPrimaryAlpha = colorAlphaGray1400
    public static let colorIconDisabled = colorGray700
    public static let colorIconQuaternary = colorGray700
    public static let colorIconTertiary = colorGray800
    public static let colorIconSecondary = colorGray900
    public static let colorIconPrimary = colorGray1400
    public static let colorBorderInfoSubtle = colorBlue500
    public static let colorBorderSuccessSubtle = colorGreen500
    public static let colorBorderCriticalSubtle = colorRed500
    public static let colorBorderCriticalHovered = colorRed1000
    public static let colorBorderCriticalPrimary = colorRed900
    public static let colorBorderInteractiveHovered = colorGray1100
    public static let colorBorderInteractiveSecondary = colorGray600
    public static let colorBorderInteractivePrimary = colorGray800
    public static let colorBorderFocused = colorBlue900
    public static let colorBorderDisabled = colorGray500
    public static let colorBgInfoSubtle = colorBlue200
    public static let colorBgSuccessSubtle = colorGreen200
    public static let colorBgCriticalSubtleHovered = colorRed300
    public static let colorBgCriticalSubtle = colorRed200
    public static let colorBgCriticalHovered = colorRed1000
    public static let colorBgCriticalPrimary = colorRed900
    public static let colorBgActionSecondaryPressed = colorAlphaGray300
    public static let colorBgActionSecondaryHovered = colorAlphaGray200
    public static let colorBgActionSecondaryRest = colorThemeBg
    public static let colorBgActionPrimaryDisabled = colorGray700
    public static let colorBgActionPrimaryPressed = colorGray1100
    public static let colorBgActionPrimaryHovered = colorGray1200
    public static let colorBgActionPrimaryRest = colorGray1400
    public static let colorBgCanvasDisabled = colorGray200
    public static let colorBgCanvasDefault = colorThemeBg
    public static let colorBgSubtleSecondary = colorGray300
    public static let colorBgSubtlePrimary = colorGray400
    public static let colorTextOnSolidPrimary = colorThemeBg
    public static let colorTextInfoPrimary = colorBlue900
    public static let colorTextSuccessPrimary = colorGreen900
    public static let colorTextCriticalPrimary = colorRed900
    public static let colorTextLinkExternal = colorBlue900
    public static let colorTextActionAccent = colorGreen900
    public static let colorTextActionPrimary = colorGray1400
    public static let colorTextDisabled = colorGray800
    public static let colorTextPlaceholder = colorGray800
    public static let colorTextSecondary = colorGray900
    public static let colorTextPrimary = colorGray1400
    public static let space64X = spaceScale * 64
    public static let space48X = spaceScale * 48
    public static let space40X = spaceScale * 40
    public static let space32X = spaceScale * 32
    public static let space28X = spaceScale * 28
    public static let space24X = spaceScale * 24
    public static let space20X = spaceScale * 20
    public static let space15X = spaceScale * 15
    public static let space14X = spaceScale * 14
    public static let space13X = spaceScale * 13
    public static let space9X = spaceScale * 9
    public static let space8X = spaceScale * 8
    public static let space7X = spaceScale * 7
    public static let space5X = spaceScale * 5
    public static let space4X = spaceScale * 4
    public static let space3X = spaceScale * 3
    public static let space2X = spaceScale * 2
    public static let space1_5X = spaceScale * 1.5
    public static let space1X = spaceScale
    public static let space0_5X = spaceScale * 0.5
}
