name: Automation
on:
  pull_request: {}
  push:
    branches: [main]
permissions: {}
jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check types
        run: yarn types

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn exec biome -- ci

  build:
    name: Check that generated files are up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build generated files
        run: yarn build
      - name: Check for changes
        run: >
          if [ -z "$(git status --porcelain)" ];
          then
            echo "Generated files are up to date."
            exit 0
          else
            echo "The files below have not been regenerated. Please run 'yarn build' to fix this."
            echo "$(git status)"
            exit 1
          fi
