name: Release npm package
on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: The scale of the version bump required for semver compatibility
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
concurrency: release
permissions:
  id-token: write # Allow npm to authenticate as a trusted publisher
  contents: write # Allow creating a release
jobs:
  release:
    name: "Release & Publish"
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.ELEMENT_BOT_TOKEN }}
          persist-credentials: true

      - name: 🔧 Set up node environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: 🛠️ Setup
        run: yarn install --pure-lockfile

      - name: 👊 Bump version
        run: |
          yarn version --no-git-tag-version --${GITHUB_EVENT_INPUTS_VERSION_BUMP}
          yarn format --write
          git config --global user.name 'ElementRobot'
          git config --global user.email 'releases@riot.im'
          git commit -am "${GITHUB_EVENT_INPUTS_VERSION_BUMP} version bump"
          git push
        env:
          GITHUB_EVENT_INPUTS_VERSION_BUMP: ${{ github.event.inputs.version-bump }}

      - name: 🚀 Publish to npm
        # We use npm since Yarn Classic doesn't support trusted publishing
        run: |
          npm publish --provenance --ignore-scripts
          echo "VERSION=$(jq '.version' --raw-output package.json)" >> "$GITHUB_ENV"

      - name: 🧬 Create release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            const { VERSION } = process.env;
            const { owner, repo } = context.repo;

            await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: `v${VERSION}`,
              name: `Release ${VERSION}`,
              body: `${VERSION} Release`,
              draft: false,
              prerelease: false,
            });
