name: Release npm package
on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: The scale of the version bump required for semver compatibility
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
concurrency: release
permissions:
  id-token: write # Allow npm to authenticate as a trusted publisher
  contents: write # Allow creating a release
jobs:
  release:
    name: "Release & Publish"
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.ELEMENT_BOT_TOKEN }}
          persist-credentials: true

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: 🔧 Set up node environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: 🛠️ Setup
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: 👊 Bump version
        run: |
          pnpm version --no-git-tag-version ${GITHUB_EVENT_INPUTS_VERSION_BUMP}
          pnpm format --write
          git config --global user.name 'ElementRobot'
          git config --global user.email 'releases@riot.im'
          git commit -am "${GITHUB_EVENT_INPUTS_VERSION_BUMP} version bump"
          git push
        env:
          GITHUB_EVENT_INPUTS_VERSION_BUMP: ${{ github.event.inputs.version-bump }}

      - name: 🚀 Publish to npm
        # We use npm directly for trusted publishing (provenance)
        run: |
          npm publish --provenance --ignore-scripts
          echo "VERSION=$(jq '.version' --raw-output package.json)" >> "$GITHUB_ENV"

      - name: 🧬 Create release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            const { VERSION } = process.env;
            const { owner, repo } = context.repo;

            await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: `v${VERSION}`,
              name: `Release ${VERSION}`,
              body: `${VERSION} Release`,
              draft: false,
              prerelease: false,
            });
